// 阅读理解数据 - 100篇（初级35/中级35/高级30）
const readingPassages = [
{id:1,title:"小蚂蚁的大力气",emoji:"🐜",color:"#fef3c7",level:"初级",
text:"小蚂蚁是自然界中力气最大的动物之一。你别看它小，它能举起比自己重50倍的东西！\n\n小蚂蚁住在地下的大房子里。它们的房子有很多房间，有放食物的仓库，有睡觉的卧室。蚂蚁们分工合作，有的找食物，有的照顾宝宝，有的保护家园。\n\n小蚂蚁非常团结。当它们发现一块大食物时，一只蚂蚁搬不动，就会跑回去叫小伙伴。大家一起用力，终于把食物搬回了家。",
questions:[
{type:"choice",question:"小蚂蚁能举起比自己重多少倍的东西？",options:["10倍","30倍","50倍","100倍"],answer:2,explain:"文章第一段说：'它能举起比自己重50倍的东西'。"},
{type:"choice",question:"小蚂蚁的家不包括以下哪个房间？",options:["仓库","卧室","看电视的客厅","照顾小蚂蚁的房间"],answer:2,explain:"文章第二段提到了仓库、卧室和照顾小蚂蚁的房间。"},
{type:"fill",question:"小蚂蚁搬不动大食物时，会怎么做？",answer:"叫小伙伴",explain:"文章第三段说：'就会跑回去叫小伙伴。'"},
{type:"choice",question:"这篇文章主要想告诉我们什么？",options:["蚂蚁很小","蚂蚁力气大而且团结","蚂蚁住在地下","蚂蚁喜欢吃东西"],answer:1,explain:"文章重点写了蚂蚁力气大和团结合作的精神。"}
]},
{id:2,title:"变色龙的魔法衣",emoji:"🦎",color:"#d1fae5",level:"初级",
text:"变色龙是一种非常奇妙的动物。它最厉害的本领就是变色。为什么要变色呢？一是为了保护自己，让敌人找不到；二是为了表达自己的心情。\n\n变色龙变色可快了。当它害怕的时候，会变成深色；当它开心的时候，会变成亮亮的颜色。在绿色的树叶上就变成绿色，在褐色的树干上就变成褐色。\n\n变色龙的眼睛也很特别。它的两只眼睛可以分开转动，一只看前面，另一只看后面，不用担心敌人从后面偷袭。",
questions:[
{type:"choice",question:"变色龙变色的原因是什么？",options:["只是为了好看","保护自己和表达心情","因为天气冷","因为生病了"],answer:1,explain:"文章第一段说：'一是为了保护自己，二是为了表达心情。'"},
{type:"choice",question:"变色龙害怕时会变成什么颜色？",options:["亮亮的颜色","深色","绿色","白色"],answer:1,explain:"文章第二段说：'当它害怕的时候，会变成深色。'"},
{type:"fill",question:"变色龙的两只眼睛可以____转动。",answer:"分开",explain:"文章第三段说：'两只眼睛可以分开转动。'"},
{type:"choice",question:"变色龙在褐色树干上会变成什么颜色？",options:["绿色","褐色","红色","黄色"],answer:1,explain:"文章第二段说：'在褐色的树干上就变成褐色。'"}
]},
{id:3,title:"诚信的小男孩",emoji:"👦",color:"#dbeafe",level:"初级",
text:"从前有一个小男孩叫明明。一天，妈妈让他去买酱油，给了他十元钱。明明买了一瓶五元钱的酱油，可是售货员阿姨找钱时却找给他十五元。原来阿姨以为他给的是二十元。\n\n明明数了数钱，发现多了十元。他心想：'这十元钱不是我的，我应该还回去。'于是他对阿姨说：'阿姨，您找错钱了，您多找了我十元。'\n\n阿姨又惊又喜，摸着他的头说：'你真是一个诚实的好孩子！'还送给他一颗糖。妈妈知道后笑着说：'你做得对，诚信比什么都重要。'",
questions:[
{type:"choice",question:"妈妈给了明明多少钱去买酱油？",options:["五元","十元","十五元","二十元"],answer:1,explain:"文章第一段说：'给了他十元。'"},
{type:"choice",question:"售货员为什么多找了十元？",options:["数学不好","以为明明给的是二十元","故意多给","看错了价格"],answer:1,explain:"文章第一段说：'阿姨以为他给的是二十元。'"},
{type:"fill",question:"明明心想这十元钱不是____的。",answer:"我",explain:"文章第二段明明心想：'这十元钱不是我的。'（答'自己'也对）"},
{type:"choice",question:"这个故事告诉我们什么道理？",options:["买东西要小心","诚信比什么都重要","要帮妈妈做事","商店会找错钱"],answer:1,explain:"文章最后妈妈说：'诚信比什么都重要。'"}
]},
{id:4,title:"神奇的含羞草",emoji:"🌿",color:"#fce7f3",level:"初级",
text:"在我家的阳台上，种着一盆含羞草。它是一种非常有趣的植物。\n\n含羞草的叶子是绿色的，小小的，排列得整整齐齐，就像羽毛一样。只要你轻轻碰它一下，它的叶子就会马上合拢起来，像害羞的小姑娘捂住了脸。过一会儿，叶子又会慢慢打开。\n\n含羞草为什么会害羞呢？原来，含羞草的叶子里有很多水分。当叶子被碰到的时候，水分就会快速流走，叶子失去了支撑，就耷拉下来了。",
questions:[
{type:"choice",question:"含羞草的叶子像什么？",options:["像手掌","像羽毛","像扇子","像爱心"],answer:1,explain:"文章第二段说：'就像羽毛一样。'"},
{type:"fill",question:"含羞草害羞的原因是叶子里有很多____。",answer:"水分",explain:"文章第三段说：'叶子里有很多水分。'（答'水'也对）"},
{type:"choice",question:"含羞草被碰后叶子会怎样？",options:["变红","合拢起来","掉落","变大"],answer:1,explain:"文章第二段说：'叶子就会马上合拢起来。'"},
{type:"choice",question:"文章用了什么修辞手法描写含羞草？",options:["比喻和拟人","夸张","排比","反问"],answer:0,explain:"'像羽毛一样'是比喻，'像害羞的小姑娘'是拟人。"}
]},
{id:5,title:"爱迪生孵蛋",emoji:"🥚",color:"#fef9c3",level:"初级",
text:"爱迪生小时候是一个非常好奇的孩子，他总是喜欢问'为什么'，还喜欢自己做实验。\n\n有一天，爱迪生看到母鸡坐在鸡蛋上，就问妈妈为什么。妈妈告诉他：'母鸡在孵蛋呢，用身体的温度把蛋暖热，小鸡就会从蛋里出来。'\n\n爱迪生听了，心想：'母鸡能孵出小鸡，我是不是也能呢？'于是他偷偷拿了一个鸡蛋，蹲在鸡窝旁边，小心翼翼地坐着。妈妈找到他时忍不住笑了：'傻孩子，人的体温太低了，孵不出小鸡的。'虽然爱迪生没有孵出小鸡，但他这种好奇和爱探索的精神，让他长大后成为了伟大的发明家。",
questions:[
{type:"choice",question:"爱迪生小时候是一个怎样的孩子？",options:["不爱说话","好奇又爱做实验","爱睡觉","不爱学习"],answer:1,explain:"文章第一段说：'非常好奇，总是喜欢问为什么，还喜欢自己做实验。'"},
{type:"choice",question:"爱迪生为什么要坐在鸡蛋上？",options:["想学母鸡孵蛋","觉得好玩","鸡窝暖和","妈妈让他做的"],answer:0,explain:"文章第三段说他心想'母鸡能孵出小鸡，我是不是也能呢'"},
{type:"fill",question:"妈妈说人的体温太____了，孵不出小鸡。",answer:"低",explain:"文章说：'人的体温太低了，孵不出小鸡的。'"},
{type:"choice",question:"这篇文章想告诉我们什么？",options:["不要做傻事","好奇心和探索精神很重要","不要模仿动物","孵蛋很难"],answer:1,explain:"文章最后说好奇和爱探索的精神让他成为了伟大的发明家。"}
]},
{id:6,title:"秋天来了",emoji:"🍂",color:"#ffedd5",level:"初级",
text:"秋天悄悄地来了，它像一位魔法师，用魔杖一点，大地就变了模样。\n\n天空变得又高又蓝，白云像棉花糖一样飘在天上。果园里，苹果红了脸，像一个个小灯笼挂在枝头。梨子穿上了黄色的新衣，葡萄披上了紫色的外套。\n\n树林里，树叶变黄了。秋风一吹，树叶纷纷落下，像一只只金色的蝴蝶在空中飞舞。菊花开了，红的、黄的、白的、紫的，争奇斗艳。",
questions:[
{type:"choice",question:"文章把秋天比作什么？",options:["画家","魔法师","仙女","诗人"],answer:1,explain:"文章第一段说：'它像一位魔法师。'"},
{type:"choice",question:"果园里没有提到哪种水果？",options:["苹果","梨子","葡萄","西瓜"],answer:3,explain:"文章第二段提到了苹果、梨子和葡萄，没有西瓜。"},
{type:"fill",question:"树叶落下时像一只只金色的____在空中飞舞。",answer:"蝴蝶",explain:"文章第三段说：'像一只只金色的蝴蝶在空中飞舞。'"},
{type:"choice",question:"文章用了什么结构来写秋天？",options:["只写了果园","先总述再分述最后总结","只写了树林","按时间顺序写"],answer:1,explain:"文章先总述秋天像魔法师，然后分别写天空、果园、树林。"}
]},
{id:7,title:"小蜗牛的房子",emoji:"🐌",color:"#e0e7ff",level:"初级",
text:"小蜗牛背着一座小房子，走到哪里就把家搬到哪里。\n\n小蜗牛的房子是螺旋形的，灰褐色的，摸上去硬硬的。这座房子虽然不大，但是很结实，能保护小蜗牛不受伤害。遇到危险的时候，小蜗牛就把身体缩进房子里，敌人就奈何不了它了。\n\n下大雨的时候，别的小动物都忙着找地方躲雨，小蜗牛却一点也不慌，因为它随时都带着自己的房子呢！",
questions:[
{type:"choice",question:"小蜗牛的房子是什么形状的？",options:["圆形","螺旋形","方形","三角形"],answer:1,explain:"文章第二段说：'房子是螺旋形的。'"},
{type:"choice",question:"遇到危险时小蜗牛会怎样？",options:["跑掉","把身体缩进房子里","叫妈妈","躲到树下"],answer:1,explain:"文章第二段说：'小蜗牛就把身体缩进房子里。'"},
{type:"fill",question:"小蜗牛的房子摸上去是____的。",answer:"硬",explain:"文章第二段说：'摸上去硬硬的。'"},
{type:"choice",question:"小蜗牛的房子有什么好处？",options:["很漂亮","能保护自己不受伤害","很轻便","很大"],answer:1,explain:"文章第二段说：'能保护小蜗牛不受伤害。'"}
]},
{id:8,title:"小水滴的旅行",emoji:"💧",color:"#ccfbf1",level:"初级",
text:"我是一颗小水滴，住在蔚蓝的大海里。有一天，太阳公公照在我身上，我觉得暖洋洋的，身体变得越来越轻，慢慢地飞上了天空。\n\n在天上，我遇到了很多小伙伴，我们聚在一起变成了白云。风伯伯一吹，我们就在天空中飘来飘去，看到了很多美丽的风景。\n\n后来天气变冷了，我和小伙伴们变成了雨滴，落到了一条小河里。小河带着我们流啊流，最后又回到了大海。这就是我的旅行！",
questions:[
{type:"choice",question:"小水滴住在哪里？",options:["小河里","大海里","天空中","白云里"],answer:1,explain:"文章第一段说：'住在蔚蓝的大海里。'"},
{type:"choice",question:"小水滴是怎么飞上天空的？",options:["风吹上去的","太阳照在身上变轻飞上去的","鸟带上去的","自己跳上去的"],answer:1,explain:"文章第一段说：'太阳公公照在我身上，身体变轻，慢慢飞上了天空。'"},
{type:"fill",question:"小水滴和小伙伴聚在一起变成了____。",answer:"白云",explain:"文章第二段说：'我们聚在一起变成了白云。'"},
{type:"choice",question:"小水滴最后回到了哪里？",options:["小河","天空","大海","地面"],answer:2,explain:"文章第三段说：'最后又回到了大海。'"}
]},
{id:9,title:"大树的四季",emoji:"🌳",color:"#dcfce7",level:"初级",
text:"我家门前有一棵大树，它一年四季都有不同的样子。\n\n春天，大树枝头冒出了嫩绿的小芽，像一个个绿色的小精灵。夏天，树叶长得密密麻麻的，像一把绿色的大伞，我们在树下乘凉。秋天，树叶变成了金黄色，风一吹就飘落下来，像金色的蝴蝶。冬天，树叶掉光了，大树光秃秃地站在那里，等待着春天的到来。",
questions:[
{type:"choice",question:"春天大树枝头冒出了什么？",options:["花朵","嫩绿的小芽","果实","黄叶"],answer:1,explain:"文章第二段说：'枝头冒出了嫩绿的小芽。'"},
{type:"choice",question:"夏天的大树像什么？",options:["一把绿色的大伞","一个巨人","一朵花","一根棍子"],answer:0,explain:"文章第三段说：'像一把绿色的大伞。'"},
{type:"fill",question:"秋天的树叶变成了____色。",answer:"金黄",explain:"文章第四段说：'树叶变成了金黄色。'（答'黄'也对）"},
{type:"choice",question:"冬天大树是什么样子？",options:["长满了果实","开满了花","光秃秃的","绿油油的"],answer:2,explain:"文章第五段说：'树叶掉光了，大树光秃秃地站在那里。'"}
]},
{id:10,title:"小蜜蜂采蜜",emoji:"🐝",color:"#fef9c3",level:"初级",
text:"春天到了，花园里百花齐放。小蜜蜂嗡嗡地飞来了，它要在花丛中采蜜呢。\n\n小蜜蜂飞到一朵红花上，把长长的嘴巴伸进花蕊里，吸呀吸，吸满了甜甜的花蜜。然后它飞到另一朵花上，继续采蜜。小蜜蜂很勤劳，从这朵花飞到那朵花，一刻也不停歇。\n\n采完蜜，小蜜蜂飞回蜂巢，把花蜜酿成蜂蜜。妈妈说蜂蜜很有营养，这都是小蜜蜂辛勤劳动的成果。",
questions:[
{type:"choice",question:"小蜜蜂在什么地方采蜜？",options:["草地上","花园里","树林里","屋顶上"],answer:1,explain:"文章第一段说：'花园里百花齐放。小蜜蜂嗡嗡地飞来了。'"},
{type:"fill",question:"小蜜蜂用长长的____伸进花蕊里吸花蜜。",answer:"嘴巴",explain:"文章第二段说：'把长长的嘴巴伸进花蕊里。'"},
{type:"choice",question:"小蜜蜂采完蜜后飞回哪里？",options:["花园","花丛","蜂巢","树上"],answer:2,explain:"文章第三段说：'小蜜蜂飞回蜂巢。'"},
{type:"choice",question:"文章想告诉我们小蜜蜂有什么品质？",options:["聪明","勤劳","勇敢","聪明"],answer:1,explain:"文章说小蜜蜂'很勤劳'，'一刻也不停歇'。"}
]},
{id:11,title:"可爱的熊猫",emoji:"🐼",color:"#f3f4f6",level:"初级",
text:"大熊猫是我们中国的国宝，它长得胖乎乎的，十分可爱。\n\n大熊猫的毛色是黑白相间的。圆圆的脑袋上有两个黑色的圆耳朵，眼睛周围有一圈黑色的毛，好像戴着一副墨镜。它走起路来摇摇晃晃的，特别有趣。\n\n大熊猫最喜欢吃竹子。它坐在地上，用两只前爪抓住竹子，咔嚓咔嚓地吃起来，吃得可香了。",
questions:[
{type:"choice",question:"大熊猫是什么毛色？",options:["全白","全黑","黑白相间","棕色"],answer:2,explain:"文章第二段说：'毛色是黑白相间的。'"},
{type:"choice",question:"大熊猫眼睛周围的毛像什么？",options:["戴了一副墨镜","戴了一副眼镜","化了妆","围了围巾"],answer:0,explain:"文章第二段说：'好像戴着一副墨镜。'"},
{type:"fill",question:"大熊猫最喜欢吃____。",answer:"竹子",explain:"文章第三段说：'大熊猫最喜欢吃竹子。'"},
{type:"choice",question:"大熊猫走起路来是什么样子？",options:["飞快地跑","摇摇晃晃的","跳着走","慢慢爬"],answer:1,explain:"文章第二段说：'走起路来摇摇晃晃的。'"}
]},
{id:12,title:"勇敢的小鹰",emoji:"🦅",color:"#dbeafe",level:"初级",
text:"一只小鹰站在悬崖边上，看着深深的峡谷，害怕得发抖。妈妈在旁边说：'孩子，你是一只鹰，你应该学会飞翔。'\n\n小鹰看了看妈妈，又看了看峡谷，还是不敢跳。妈妈说：'不要怕，我会在下面接住你的。'小鹰深吸一口气，闭上眼睛，张开翅膀，跳了下去。\n\n风在耳边呼呼地吹，小鹰睁开眼睛，发现自己居然飞起来了！它高兴地叫着：'妈妈，我会飞了！'妈妈在旁边笑着说：'你真勇敢！'",
questions:[
{type:"choice",question:"小鹰为什么站在悬崖边发抖？",options:["因为冷","因为害怕","因为饿了","因为生病了"],answer:1,explain:"文章第一段说：'看着深深的峡谷，害怕得发抖。'"},
{type:"fill",question:"妈妈说不要怕，会在下面____小鹰的。",answer:"接住",explain:"文章第二段说：'我会在下面接住你的。'"},
{type:"choice",question:"小鹰跳下去后发现了什么？",options:["自己摔倒了","自己飞起来了","妈妈接住了它","什么也没发生"],answer:1,explain:"文章第三段说：'发现自己居然飞起来了！'"},
{type:"choice",question:"这个故事告诉我们什么道理？",options:["飞翔很危险","要勇敢尝试","不要听妈妈的话","悬崖很深"],answer:1,explain:"小鹰勇敢跳下去后发现自己能飞，说明要勇敢尝试。"}
]},
{id:13,title:"小草的力量",emoji:"🌱",color:"#d1fae5",level:"初级",
text:"有人做过一个实验：在花盆里放一些种子，然后压上一块石头。过了一些日子，种子发芽了，小草居然从石头旁边弯弯曲曲地长了出来。\n\n小草的力量看起来很小，但是它从不放弃。不管石头有多重，不管路有多弯，它总要找到缝隙，努力向上生长。终于有一天，它见到了阳光。\n\n小草告诉我们：只要不放弃，再大的困难也能克服。",
questions:[
{type:"choice",question:"实验中花盆里压着什么？",options:["一块砖头","一块石头","一本书","一块木板"],answer:1,explain:"文章第一段说：'压上一块石头。'"},
{type:"fill",question:"小草从石头旁边____地长了出来。",answer:"弯弯曲曲",explain:"文章第一段说：'弯弯曲曲地长了出来。'"},
{type:"choice",question:"小草的力量虽然小，但它有什么品质？",options:["从不放弃","速度很快","力气很大","颜色很绿"],answer:0,explain:"文章第二段说：'小草的力量看起来很小，但是它从不放弃。'"},
{type:"choice",question:"小草告诉我们什么道理？",options:["石头很重","只要不放弃就能克服困难","种子很有力量","阳光很重要"],answer:1,explain:"文章最后一段说：'只要不放弃，再大的困难也能克服。'"}
]},
{id:14,title:"月亮姑娘做衣裳",emoji:"🌙",color:"#e0e7ff",level:"初级",
text:"月亮姑娘想做一件衣裳。她去找裁缝量尺寸，可是她每天都在变化。\n\n初一的时候，月亮姑娘瘦瘦的，像一条小船。裁缝给她量好了尺寸，可过了几天，月亮姑娘胖了一些，衣裳穿不上了。到了十五，月亮姑娘变得圆圆的，像一个大盘子，之前的衣裳更穿不上了。\n\n裁缝叹了口气说：'你的身材天天在变，我没法给你做衣裳啊！'",
questions:[
{type:"choice",question:"月亮姑娘为什么要做衣裳？",options:["冷了","想做衣裳","妈妈让做的","好看"],answer:1,explain:"文章第一段说：'月亮姑娘想做一件衣裳。'"},
{type:"choice",question:"初一的时候月亮像什么？",options:["一个大盘子","一条小船","一个圆球","一把镰刀"],answer:1,explain:"文章第二段说：'初一的时候，月亮姑娘瘦瘦的，像一条小船。'"},
{type:"fill",question:"十五的时候月亮姑娘变得____的。",answer:"圆圆",explain:"文章第三段说：'月亮姑娘变得圆圆的。'"},
{type:"choice",question:"裁缝为什么没法做衣裳？",options:["裁缝手艺不好","月亮姑娘身材天天在变","没有布料","月亮姑娘不要了"],answer:1,explain:"文章说月亮姑娘每天都在变化，所以没法做。"}
]},
{id:15,title:"雪花的故事",emoji:"❄️",color:"#dbeafe",level:"初级",
text:"冬天来了，天空飘下了美丽的雪花。雪花是白色的，有六个角，像一朵朵白色的小花从天上落下来。\n\n雪花落在屋顶上，屋顶变白了。雪花落在树上，树穿上了白棉袄。雪花落在大地上，大地铺上了白地毯。整个世界变成了银白色的，好美啊！\n\n小朋友们在雪地上堆雪人、打雪仗，欢声笑语回荡在空中。雪花给冬天带来了快乐。",
questions:[
{type:"choice",question:"雪花有几个角？",options:["四个","五个","六个","八个"],answer:2,explain:"文章第一段说：'有六个角。'"},
{type:"fill",question:"雪花落在树上，树穿上了____。",answer:"白棉袄",explain:"文章第二段说：'树穿上了白棉袄。'"},
{type:"choice",question:"文章没有写雪花落在什么地方？",options:["屋顶上","树上","大地上","河里"],answer:3,explain:"文章写了屋顶、树上、大地上，没有写河里。"},
{type:"choice",question:"雪花给冬天带来了什么？",options:["寒冷","快乐","麻烦","危险"],answer:1,explain:"文章最后说：'雪花给冬天带来了快乐。'"}
]},
{id:16,title:"知了唱歌",emoji:" cicada",color:"#fef3c7",level:"初级",
text:"夏天到了，知了在树上知了知了地叫个不停。\n\n知了的声音很响亮，一只知了叫起来，旁边的知了也跟着叫，好像在比赛谁的嗓门大。可是你知道吗？知了不是用嘴巴唱歌的，而是用肚子上的一个发音膜来发声的。\n\n只有雄知了才会唱歌，雌知了是不会唱歌的。雄知了唱歌是为了吸引雌知了，就像在说：'快来呀，我在这里！'",
questions:[
{type:"choice",question:"知了用什么唱歌？",options:["嘴巴","发音膜","翅膀","脚"],answer:1,explain:"文章第二段说：'用肚子上的一个发音膜来发声的。'"},
{type:"choice",question:"哪种知了会唱歌？",options:["雌知了","雄知了","都会","都不会"],answer:1,explain:"文章第三段说：'只有雄知了才会唱歌。'"},
{type:"fill",question:"雄知了唱歌是为了____雌知了。",answer:"吸引",explain:"文章第三段说：'雄知了唱歌是为了吸引雌知了。'"},
{type:"choice",question:"知了的声音是怎样的？",options:["很小声","很响亮","很沙哑","很难听"],answer:1,explain:"文章第二段说：'知了的声音很响亮。'"}
]},
{id:17,title:"小松鼠存粮",emoji:"🐿️",color:"#d1fae5",level:"初级",
text:"秋天到了，小松鼠忙着储存过冬的食物。\n\n小松鼠在树林里跑来跑去，找到一颗松果就抱回树洞里。它一天要跑很多趟，有时候一趟只能搬一颗松果，有时候一趟能搬好几颗。它把松果、榛子都藏在树洞的深处。\n\n冬天来了，外面下着大雪，小松鼠在温暖的树洞里吃着秋天存的食物，一点也不担心饿肚子。提前做好准备真重要啊！",
questions:[
{type:"choice",question:"小松鼠在什么季节储存食物？",options:["春天","夏天","秋天","冬天"],answer:2,explain:"文章第一段说：'秋天到了，小松鼠忙着储存过冬的食物。'"},
{type:"fill",question:"小松鼠把食物藏在____的深处。",answer:"树洞",explain:"文章第二段说：'藏在树洞的深处。'"},
{type:"choice",question:"小松鼠存了什么食物？",options:["松果和榛子","苹果和梨","玉米和稻谷","面包和饼干"],answer:0,explain:"文章第二段说：'把松果、榛子都藏在树洞的深处。'"},
{type:"choice",question:"冬天小松鼠为什么不担心饿肚子？",options:["因为有很多朋友","因为提前存了食物","因为冬天有食物","因为不饿"],answer:1,explain:"文章第三段说：'小松鼠在温暖的树洞里吃着秋天存的食物。'"}
]},
{id:18,title:"彩虹桥",emoji:"🌈",color:"#fce7f3",level:"初级",
text:"下了一场大雨后，太阳出来了，天空中出现了一道美丽的彩虹。\n\n彩虹有七种颜色：红、橙、黄、绿、青、蓝、紫。它像一座弯弯的桥挂在天上，所以人们叫它彩虹桥。小鸟飞过彩虹，好像在桥上散步呢。\n\n彩虹很美，但它不会一直待在天上。过一会儿就慢慢消失了。妈妈说彩虹是阳光照在小水滴上形成的。彩虹虽然短暂，但它的美丽留在了我们心里。",
questions:[
{type:"choice",question:"彩虹在什么时候出现？",options:["下雪后","下雨后出太阳时","早上","晚上"],answer:1,explain:"文章第一段说：'下了一场大雨后，太阳出来了，天空中出现了彩虹。'"},
{type:"fill",question:"彩虹有____种颜色。",answer:"七",explain:"文章第二段说：'彩虹有七种颜色。'"},
{type:"choice",question:"彩虹像什么？",options:["一把扇子","一座弯弯的桥","一条丝带","一个圆环"],answer:1,explain:"文章第二段说：'像一座弯弯的桥挂在天上。'"},
{type:"choice",question:"彩虹是怎么形成的？",options:["画家画的","阳光照在小水滴上形成的","天上的灯","云变的"],answer:1,explain:"文章第四段说：'彩虹是阳光照在小水滴上形成的。'"}
]},
{id:19,title:"小马过河",emoji:"🐴",color:"#fef3c7",level:"初级",
text:"小马要过一条河，不知道河水有多深。牛伯伯说：'水很浅，刚到小腿，能过。'小松鼠却说：'水很深，昨天我的朋友就被淹死了！'\n\n小马不知道该听谁的，回去问妈妈。妈妈说：'你为什么不自己试试呢？'\n\n小马回到河边，小心地把前蹄伸进水里。河水既不像牛伯伯说的那么浅，也不像小松鼠说的那么深。小马顺利地过了河。",
questions:[
{type:"choice",question:"牛伯伯说河水怎样？",options:["很深","很浅","很脏","很急"],answer:1,explain:"文章第一段牛伯伯说：'水很浅，刚到小腿。'"},
{type:"choice",question:"小松鼠说河水怎样？",options:["很浅","很深","很干净","很温暖"],answer:1,explain:"文章第一段小松鼠说：'水很深。'"},
{type:"fill",question:"妈妈说为什么不自己____呢？",answer:"试试",explain:"文章第二段妈妈说：'你为什么不自己试试呢？'"},
{type:"choice",question:"这个故事告诉我们什么道理？",options:["要听大人的话","要自己亲自去尝试","不要过河","河很危险"],answer:1,explain:"小马自己试了才发现河水既不深也不浅，说明要亲自尝试。"}
]},
{id:20,title:"猫头鹰",emoji:"🦉",color:"#e0e7ff",level:"初级",
text:"猫头鹰是一种奇怪的鸟，它白天睡觉，晚上出来活动。\n\n猫头鹰的眼睛很大很亮，在黑夜里也能看得清清楚楚。它的耳朵也很灵敏，能听到地面上小老鼠走动的声音。猫头鹰的脑袋能转二百七十度，不用转身就能看到后面的东西。\n\n猫头鹰是捕捉老鼠的高手。一个晚上，一只猫头鹰能捉好几只老鼠呢。农民伯伯可喜欢猫头鹰了。",
questions:[
{type:"choice",question:"猫头鹰什么时候出来活动？",options:["白天","晚上","中午","黄昏"],answer:1,explain:"文章第一段说：'白天睡觉，晚上出来活动。'"},
{type:"fill",question:"猫头鹰的脑袋能转____度。",answer:"二百七十",explain:"文章第三段说：'脑袋能转二百七十度。'（答'270'也对）"},
{type:"choice",question:"猫头鹰是捕捉什么的高手？",options:["害虫","老鼠","鱼","蛇"],answer:1,explain:"文章第四段说：'猫头鹰是捕捉老鼠的高手。'"},
{type:"choice",question:"为什么农民伯伯喜欢猫头鹰？",options:["因为好看","因为它能捉老鼠保护庄稼","因为叫声好听","因为不怕黑"],answer:1,explain:"猫头鹰捉老鼠，保护了庄稼，所以农民伯伯喜欢它。"}
]},
{id:21,title:"种子的旅行",emoji:"🌰",color:"#d1fae5",level:"初级",
text:"蒲公英的种子想出去旅行。一阵风吹来，种子们撑开白色的小伞，飞了起来。\n\n有的种子飞到了山坡上，有的飞到了小河边，有的飞到了田野里。它们在新的地方安家落户，等到春天，就会长出新的蒲公英。\n\n除了风，水也能帮种子旅行。椰子掉进海里，漂啊漂，漂到了另一个岛上，就在那里生根发芽了。大自然真神奇啊！",
questions:[
{type:"choice",question:"蒲公英的种子靠什么旅行？",options:["水","风","动物","人"],answer:1,explain:"文章第一段说：'一阵风吹来，种子们撑开白色的小伞，飞了起来。'"},
{type:"fill",question:"蒲公英的种子撑开白色的小____飞起来。",answer:"伞",explain:"文章第一段说：'撑开白色的小伞，飞了起来。'"},
{type:"choice",question:"什么种子靠水旅行？",options:["蒲公英","椰子","苹果","松果"],answer:1,explain:"文章第三段说：'椰子掉进海里，漂啊漂，漂到了另一个岛上。'"},
{type:"choice",question:"种子旅行的目的是什么？",options:["好玩","在新的地方安家落户","找朋友","晒太阳"],answer:1,explain:"文章第二段说：'在新的地方安家落户。'"}
]},
{id:22,title:"星星为什么会眨眼",emoji:"⭐",color:"#e0e7ff",level:"初级",
text:"夏天的晚上，我们仰望天空，看到星星一闪一闪的，好像在眨眼睛。星星为什么会眨眼呢？\n\n其实星星发出的光是稳定的，不会一闪一闪。但是我们地球外面有一层厚厚的大气层，大气层里的空气在不停地流动，有的地方密，有的地方疏。\n\n星光穿过大气层时，就会被流动的空气折射，一会儿偏这边，一会儿偏那边，我们看上去就像星星在眨眼睛一样。",
questions:[
{type:"choice",question:"星星眨眼是因为什么？",options:["星星本身在闪","大气层里的空气在流动","眼睛花了","云在挡"],answer:1,explain:"文章第三段说星穿过流动的大气层时被折射，看上去像在眨眼。"},
{type:"fill",question:"地球外面有一层厚厚的____层。",answer:"大气",explain:"文章第二段说：'地球外面有一层厚厚的大气层。'"},
{type:"choice",question:"星星发出的光实际上是怎样的？",options:["一闪一闪的","稳定的","很暗的","彩色的"],answer:1,explain:"文章第二段说：'星星发出的光是稳定的，不会一闪一闪。'"},
{type:"choice",question:"星光穿过大气层时会被什么？",options:["吸收","反射","折射","阻挡"],answer:2,explain:"文章第三段说：'星光穿过大气层时，就会被流动的空气折射。'"}
]},
{id:23,title:"节约用水",emoji:"💧",color:"#ccfbf1",level:"初级",
text:"水是生命之源，我们每天都要用水。可是你知道吗？地球上能喝的淡水越来越少。\n\n洗手的时候，水龙头不要一直开着。洗澡的时候，用淋浴比泡澡省水。洗菜的水可以用来浇花，淘米的水可以用来洗碗。\n\n如果我们每个人每天节约一滴水，全国加起来就是很多很多水。节约用水，从我做起，从现在做起！",
questions:[
{type:"choice",question:"地球上的淡水怎么样？",options:["越来越多","越来越少","不变","用不完"],answer:1,explain:"文章第一段说：'地球上能喝的淡水越来越少。'"},
{type:"fill",question:"洗菜的水可以用来____。",answer:"浇花",explain:"文章第二段说：'洗菜的水可以用来浇花。'"},
{type:"choice",question:"哪种洗澡方式更省水？",options:["泡澡","淋浴","盆浴","都一样"],answer:1,explain:"文章第二段说：'用淋浴比泡澡省水。'"},
{type:"choice",question:"这篇文章主要想告诉我们什么？",options:["水很有用","要节约用水","水很珍贵","洗澡要省水"],answer:1,explain:"文章最后说：'节约用水，从我做起。'"}
]},
{id:24,title:"小壁虎借尾巴",emoji:"🦎",color:"#d1fae5",level:"初级",
text:"小壁虎的尾巴被蛇咬断了，它很难过，决定去借一条尾巴。\n\n它找到小鱼，问：'鱼姐姐，你的尾巴借给我好吗？'小鱼说：'不行啊，我要用尾巴游泳呢。'它找到老牛，老牛说：'不行啊，我要用尾巴赶蝇子呢。'\n\n小壁虎伤心地回家了。妈妈看到它笑着说：'你转身看看。'小壁虎转身一看，自己长出了一条新尾巴！原来壁虎的尾巴断了还会再长出来。",
questions:[
{type:"choice",question:"小壁虎为什么去借尾巴？",options:["尾巴不好看","尾巴被蛇咬断了","想换一条","尾巴太短"],answer:1,explain:"文章第一段说：'尾巴被蛇咬断了。'"},
{type:"fill",question:"小鱼要用尾巴____。",answer:"游泳",explain:"文章第二段小鱼说：'我要用尾巴游泳呢。'"},
{type:"choice",question:"老牛用尾巴做什么？",options:["游泳","赶蝇子","走路","保暖"],answer:1,explain:"文章第二段老牛说：'我要用尾巴赶蝇子呢。'"},
{type:"choice",question:"壁虎的尾巴有什么特点？",options:["很长","断了会再长出来","很漂亮","很有力"],answer:1,explain:"文章第三段说：'壁虎的尾巴断了还会再长出来。'"}
]},
{id:25,title:"蚂蚁搬家",emoji:"🐜",color:"#fef3c7",level:"初级",
text:"放学回家路上，我看到一群蚂蚁在搬家。它们排着长长的队伍，有的背着食物，有的扛着蚁卵，急急忙忙地往前走。\n\n我问妈妈蚂蚁为什么要搬家。妈妈说：'蚂蚁搬家是要下雨了。蚂蚁能感觉到天气的变化，它们要把家搬到高处，免得被雨水淹没。'\n\n果然，到了傍晚就下起了大雨。蚂蚁们真厉害，能预测天气的变化呢！",
questions:[
{type:"choice",question:"蚂蚁搬家是什么预兆？",options:["要刮风了","要下雨了","要天晴了","要下雪了"],answer:1,explain:"文章第二段妈妈说：'蚂蚁搬家是要下雨了。'"},
{type:"fill",question:"蚂蚁要把家搬到____，免得被雨水淹没。",answer:"高处",explain:"文章第二段说：'要把家搬到高处。'"},
{type:"choice",question:"蚂蚁搬家时排着什么样的队伍？",options:["短短的","长长的","弯弯的","乱七八糟的"],answer:1,explain:"文章第一段说：'排着长长的队伍。'"},
{type:"choice",question:"蚂蚁能做什么？",options:["能说话","能预测天气","能飞","能游泳"],answer:1,explain:"文章第三段说：'蚂蚁能预测天气的变化。'"}
]},
{id:26,title:"大海的礼物",emoji:"🐚",color:"#ccfbf1",level:"初级",
text:"今天我和妈妈去海边玩。大海蓝蓝的，波浪哗哗地拍打着沙滩。\n\n沙滩上有好多美丽的贝壳！有白色的、粉色的、黄色的，形状也各不相同，有的像扇子，有的像小喇叭，有的像星星。我捡了满满一口袋。\n\n我还看到了一只小螃蟹，它横着走路，一会儿就钻进了沙洞里，好像在和我捉迷藏。大海真是一位慷慨的朋友，给我们带来了这么多礼物！",
questions:[
{type:"choice",question:"大海是什么颜色的？",options:["绿色的","蓝色的","黄色的","白色的"],answer:1,explain:"文章第一段说：'大海蓝蓝的。'"},
{type:"fill",question:"沙滩上的贝壳有的像____，有的像小喇叭。",answer:"扇子",explain:"文章第二段说：'有的像扇子，有的像小喇叭。'"},
{type:"choice",question:"小螃蟹是怎么走路的？",options:["直着走","横着走","倒着走","跳着走"],answer:1,explain:"文章第三段说：'它横着走路。'"},
{type:"choice",question:"文章说大海是一位怎样的朋友？",options:["美丽的","慷慨的","安静的","勇敢的"],answer:1,explain:"文章最后说：'大海真是一位慷慨的朋友。'"}
]},
{id:27,title:"乌鸦喝水",emoji:"🐦",color:"#e0e7ff",level:"初级",
text:"一只乌鸦口渴了，到处找水喝。它看到一个瓶子里有水，可是瓶子很高，瓶口很小，里面的水又不多，乌鸦喝不着。\n\n乌鸦看到旁边有很多小石子，想出了一个好办法。它把石子一个一个地衔起来，放到瓶子里。瓶子里的水渐渐升高了，乌鸦就喝着水了。\n\n遇到困难不要怕，动动脑筋总能找到办法。",
questions:[
{type:"choice",question:"乌鸦为什么喝不到瓶子里的水？",options:["水太少了","瓶子太高瓶口太小","水太深","瓶子太重"],answer:1,explain:"文章第一段说：'瓶子很高，瓶口很小，里面的水又不多。'"},
{type:"fill",question:"乌鸦把____一个一个放到瓶子里。",answer:"石子",explain:"文章第二段说：'把石子一个一个地衔起来，放到瓶子里。'（答'小石子'也对）"},
{type:"choice",question:"乌鸦用什么办法喝到了水？",options:["把瓶子推倒","往瓶子里放石子让水升高","用吸管","把瓶子打破"],answer:1,explain:"文章第二段说乌鸦往瓶子里放石子，水升高后就喝到了。"},
{type:"choice",question:"这个故事告诉我们什么道理？",options:["瓶子很高","遇到困难动脑筋就能找到办法","乌鸦很聪明","石子很有用"],answer:1,explain:"文章最后说：'遇到困难不要怕，动动脑筋总能找到办法。'"}
]},
{id:28,title:"向日葵",emoji:"🌻",color:"#fef9c3",level:"初级",
text:"我家院子里种了几棵向日葵。它们高高的，叶子大大的，金黄色的花盘圆圆的，像一个个小太阳。\n\n向日葵有一个特别的本领：它的花盘总是朝着太阳的方向。早上太阳从东边升起，花盘就朝东；下午太阳到了西边，花盘就朝西。所以人们叫它向日葵。\n\n秋天到了，向日葵的花盘里结满了瓜子。我剥了一颗，真香啊！向日葵不仅好看，还能给我们好吃的瓜子呢。",
questions:[
{type:"choice",question:"向日葵的花盘像什么？",options:["小月亮","小太阳","小星星","小灯笼"],answer:1,explain:"文章第一段说：'金黄色的花盘圆圆的，像一个个小太阳。'"},
{type:"fill",question:"向日葵的花盘总是朝着____的方向。",answer:"太阳",explain:"文章第二段说：'花盘总是朝着太阳的方向。'"},
{type:"choice",question:"向日葵的果实是什么？",options:["花生","瓜子","核桃","枣"],answer:1,explain:"文章第三段说：'花盘里结满了瓜子。'"},
{type:"choice",question:"向日葵得名是因为什么？",options:["花长得像太阳","花盘总是向着太阳","花是金色的","长得很高"],answer:1,explain:"文章第二段说：'花盘总是朝着太阳的方向，所以人们叫它向日葵。'"}
]},
{id:29,title:"小鸟学飞",emoji:"🐦",color:"#d1fae5",level:"初级",
text:"一只小鸟长大了，鸟妈妈教它学飞。小鸟站在窝边，看着下面好高好高，害怕地缩了回去。\n\n鸟妈妈鼓励它：'别怕，张开翅膀，用力扇。'小鸟试着张开翅膀，使劲扇了几下，身体晃了晃，掉下去了。幸好它掉在了一堆软草上，没有受伤。\n\n小鸟又爬上去，这一次它更用力地扇翅膀。慢慢地，它不再往下掉了，而是越飞越高。小鸟高兴地叫着：'妈妈，我会飞了！'",
questions:[
{type:"choice",question:"小鸟为什么不敢飞？",options:["翅膀没长好","觉得太高害怕","妈妈不让飞","太累了"],answer:1,explain:"文章第一段说：'看着下面好高好高，害怕地缩了回去。'"},
{type:"fill",question:"小鸟第一次飞掉在了____上。",answer:"软草",explain:"文章第二段说：'掉在了一堆软草上。'"},
{type:"choice",question:"小鸟最后飞起来了吗？",options:["没有飞起来","飞起来了","摔伤了","放弃了"],answer:1,explain:"文章第三段说：'越飞越高。小鸟高兴地叫着：我会飞了！'"},
{type:"choice",question:"小鸟学飞告诉我们什么道理？",options:["飞很危险","不要怕失败，坚持就能成功","草堆很有用","鸟妈妈很厉害"],answer:1,explain:"小鸟第一次失败了但没放弃，第二次终于飞起来了。"}
]},
{id:30,title:"风在哪里",emoji:"🌬️",color:"#dbeafe",level:"初级",
text:"风看不见摸不着，可是我们能感觉到它。\n\n风在哪里呢？你看，树叶在摇晃，那是风在跳舞。你看，旗帜在飘扬，那是风在招手。你看，水面起了波纹，那是风在画画。\n\n风有时温柔，轻轻地吹在脸上，像妈妈的手抚摸着你。风有时调皮，把你的帽子吹跑，把雨伞吹翻。风有时凶猛，刮倒大树，掀翻屋顶。风真是变化多端啊！",
questions:[
{type:"choice",question:"风是什么样的？",options:["看得见摸得着","看不见摸不着","只看得见","只摸得着"],answer:1,explain:"文章第一段说：'风看不见摸不着。'"},
{type:"fill",question:"树叶在摇晃，那是风在____。",answer:"跳舞",explain:"文章第二段说：'树叶在摇晃，那是风在跳舞。'"},
{type:"choice",question:"温柔的风吹在脸上像什么？",options:["爸爸的手","妈妈的手","老师的 手","朋友的手"],answer:1,explain:"文章第三段说：'像妈妈的手抚摸着你。'"},
{type:"choice",question:"文章写了风的几种样子？",options:["一种","两种","三种","四种"],answer:2,explain:"文章写了温柔的风、调皮的风和凶猛的风三种。"}
]},
{id:31,title:"小兔子的长耳朵",emoji:"🐰",color:"#fce7f3",level:"初级",
text:"小兔子有一对长长的耳朵，它有时觉得很自豪，有时又觉得不方便。\n\n自豪的是，它的长耳朵特别灵敏，能听到很远很远的声音。老鹰来了，它老远就能听到翅膀扇动的声音，赶紧躲起来。不方便的是，睡觉的时候长耳朵总是碍事，翻个身就压到了。\n\n有一天小兔子问妈妈：'我的耳朵为什么这么长？'妈妈笑着说：'长耳朵是我们兔子的宝贝，能保护我们的安全呀。'小兔子听了，再也不嫌弃自己的长耳朵了。",
questions:[
{type:"choice",question:"小兔子的长耳朵有什么好处？",options:["很好看","特别灵敏能听到很远的声音","能飞","能扇风"],answer:1,explain:"文章第二段说：'长耳朵特别灵敏，能听到很远很远的声音。'"},
{type:"fill",question:"小兔子能听到____飞来的声音，赶紧躲起来。",answer:"老鹰",explain:"文章第二段说：'老鹰来了，它老远就能听到翅膀扇动的声音。'"},
{type:"choice",question:"长耳朵什么时候不方便？",options:["走路时","睡觉时","吃饭时","跑步时"],answer:1,explain:"文章第二段说：'睡觉的时候长耳朵总是碍事。'"},
{type:"choice",question:"妈妈说长耳朵是什么？",options:["装饰","宝贝","麻烦","没用"],answer:1,explain:"文章第三段妈妈说：'长耳朵是我们兔子的宝贝。'"}
]},
{id:32,title:"四季的风",emoji:"🍃",color:"#d1fae5",level:"初级",
text:"一年四季都有风，但每个季节的风都不一样。\n\n春天的风暖暖的，吹在脸上很舒服。春风一吹，小草绿了，花儿开了，大地变得生机勃勃。\n\n夏天的风热热的，吹在身上黏糊糊的。但夏天的风带着荷花的清香，让人觉得还不错。\n\n秋天的风凉凉的，吹黄了树叶，吹红了苹果。秋风一吹，果园里硕果累累。\n\n冬天的风冷冷的，呼呼地刮着，像刀子一样割在脸上。但冬风也带来了洁白的雪花。",
questions:[
{type:"choice",question:"春天的风是怎样的？",options:["暖暖的","热热的","凉凉的","冷冷的"],answer:0,explain:"文章第二段说：'春天的风暖暖的。'"},
{type:"fill",question:"秋天的风吹红了____。",answer:"苹果",explain:"文章第四段说：'吹黄了树叶，吹红了苹果。'"},
{type:"choice",question:"冬天的风像什么？",options:["妈妈的手","刀子","棉花","丝绸"],answer:1,explain:"文章第五段说：'像刀子一样割在脸上。'"},
{type:"choice",question:"夏天的风带着什么香味？",options:["玫瑰花香","荷花清香","桂花香","梅花香"],answer:1,explain:"文章第三段说：'夏天的风带着荷花的清香。'"}
]},
{id:33,title:"萤火虫的小灯笼",emoji:"✨",color:"#fef9c3",level:"初级",
text:"夏天的夜晚，草丛里一闪一闪的，那是萤火虫提着小灯笼在飞。\n\n萤火虫的尾巴会发光，一闪一闪的，像一盏小灯笼。它在夜空中飞来飞去，好像在给小虫子们照路。\n\n萤火虫为什么要发光呢？原来这是它们在找朋友。萤火虫用闪光来告诉同伴：'我在这里，快来找我呀！'可是现在城市里灯光太亮了，萤火虫越来越少了。真希望萤火虫能越来越多。",
questions:[
{type:"choice",question:"萤火虫哪里会发光？",options:["头部","翅膀","尾巴","脚"],answer:2,explain:"文章第二段说：'萤火虫的尾巴会发光。'"},
{type:"fill",question:"萤火虫发光像一盏小____。",answer:"灯笼",explain:"文章第二段说：'像一盏小灯笼。'"},
{type:"choice",question:"萤火虫发光是为了什么？",options:["照亮路","找朋友","吓唬敌人","取暖"],answer:1,explain:"文章第三段说：'这是它们在找朋友。'"},
{type:"choice",question:"为什么萤火虫越来越少了？",options:["被捉光了","城市灯光太亮","没有食物","太热了"],answer:1,explain:"文章第三段说：'城市里灯光太亮了，萤火虫越来越少了。'"}
]},
{id:34,title:"小蝌蚪找妈妈",emoji:"🐸",color:"#d1fae5",level:"初级",
text:"池塘里有一群小蝌蚪，大大的脑袋，黑灰色的身子，甩着长长的尾巴。它们看到鸭妈妈带着小鸭子游过，想起自己的妈妈，就决定去找。\n\n它们问鲤鱼妈妈，鲤鱼说：'你们的妈妈有四条腿，宽嘴巴。'它们看到乌龟，就叫妈妈，乌龟说：'我不是你们的妈妈，你们的妈妈头顶上有两只大眼睛。'\n\n最后它们找到了青蛙妈妈。青蛙妈妈说：'好孩子，你们已经长成青蛙了，快跳上来吧！'小蝌蚪一看，自己也不知道什么时候长了四条腿，尾巴也不见了。",
questions:[
{type:"choice",question:"小蝌蚪长什么样？",options:["四条腿长尾巴","大大的脑袋长尾巴","绿色的小身体","有翅膀"],answer:1,explain:"文章第一段说：'大大的脑袋，黑灰色的身子，甩着长长的尾巴。'"},
{type:"fill",question:"鲤鱼说小蝌蚪的妈妈有____条腿。",answer:"四",explain:"文章第二段鲤鱼说：'你们的妈妈有四条腿。'"},
{type:"choice",question:"小蝌蚪错认谁为妈妈？",options:["鲤鱼","乌龟","鸭子","蛇"],answer:1,explain:"文章第二段说：'看到乌龟，就叫妈妈。'"},
{type:"choice",question:"小蝌蚪最后变成了什么？",options:["鲤鱼","乌龟","青蛙","蛇"],answer:2,explain:"文章第三段青蛙妈妈说：'你们已经长成青蛙了。'"}
]},
{id:35,title:"桥",emoji:"🌉",color:"#e0e7ff",level:"初级",
text:"我家门前有一条小河，河上有一座石桥。这座桥已经有一百多岁了，桥上长满了青苔。\n\n每天早晨，爷爷都到桥上打太极拳。放学后，我和小伙伴们在桥上玩，看桥下的鱼儿游来游去。桥下，小船经常从桥洞里穿过，船夫唱着歌，声音在桥洞里回荡。\n\n这座老桥默默地站在那里，不管风吹雨打，也不抱怨。它连接着河的两岸，让人们的来往变得方便。我爱这座老桥。",
questions:[
{type:"choice",question:"文中的桥是什么材料的？",options:["木头","石头","水泥","钢铁"],answer:1,explain:"文章第一段说：'河上有一座石桥。'"},
{type:"fill",question:"桥上长满了____。",answer:"青苔",explain:"文章第一段说：'桥上长满了青苔。'"},
{type:"choice",question:"爷爷在桥上做什么？",options:["散步","打太极拳","下棋","看书"],answer:1,explain:"文章第二段说：'爷爷都到桥上打太极拳。'"},
{type:"choice",question:"老桥有什么品质？",options:["很坚固","默默奉献不抱怨","很漂亮","很古老"],answer:1,explain:"文章第三段说：'不管风吹雨打，也不抱怨。它连接着河的两岸。'"}
]},
{id:36,title:"骄傲的孔雀",emoji:"🦚",color:"#fce7f3",level:"中级",text:"孔雀有美丽的羽毛,展尾如扇,所有动物都赞叹。渐渐地孔雀变得骄傲,看不起别的小动物,说麻雀太丑,说乌鸦太黑。下雨淋湿羽毛,没人愿意帮它,只有小麻雀收留了它。孔雀惭愧地低下了头,从此再也不骄傲了。",questions:[{type:"choice",question:"孔雀为什么变得骄傲",options:["力气大","羽毛美丽被赞叹","跑得快","聪明"],answer:1,explain:"答案是：羽毛美丽被赞叹。"},{type:"fill",question:"下雨后孔雀的羽毛又脏又___。",answer:"乱",explain:"答案是：乱。"},{type:"choice",question:"谁收留了孔雀",options:["乌鸦","小鸡","小麻雀","没人"],answer:2,explain:"答案是：小麻雀。"},{type:"fill",question:"这个故事告诉我们什么",answer:"不要骄傲要友善待人",explain:"答案是：不要骄傲要友善待人。"}]},
{id:37,title:"滴水穿石",emoji:"💧",color:"#dbeafe",level:"中级",text:"安徽太极洞有块石头被水滴穿了个洞。水滴日复一日年复一年滴在同一个地方,经过几百年几千年,坚硬的石头被穿了一个洞。只要有恒心有毅力坚持不懈就能成功。",questions:[{type:"choice",question:"水滴穿石在安徽哪里",options:["太极洞","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：太极洞。"},{type:"fill",question:"水滴总是滴在___的地方",answer:"同一个",explain:"答案是：同一个。"},{type:"choice",question:"石头被穿用了多久",options:["几百年几千年","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：几百年几千年。"},{type:"fill",question:"滴水穿石告诉我们什么",answer:"只要有恒心有毅力坚持就能成功",explain:"答案是：只要有恒心有毅力坚持就能成功。"},]},
{id:38,title:"蝙蝠的雷达",emoji:"🦇",color:"#dbeafe",level:"中级",text:"蝙蝠夜里飞行不撞东西。科学家蒙住蝙蝠眼睛它飞得很好,蒙住耳朵就到处乱撞。原来蝙蝠嘴里发出超声波,碰到障碍物反射回来,耳朵接收回声判断方向。科学家据此发明了雷达。",questions:[{type:"choice",question:"蝙蝠靠什么避开障碍",options:["耳朵听回声","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：耳朵听回声。"},{type:"fill",question:"蒙住___后到处乱撞",answer:"耳朵",explain:"答案是：耳朵。"},{type:"choice",question:"蒙住眼睛后怎样",options:["飞得很好没碰东西","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：飞得很好没碰东西。"},{type:"fill",question:"根据蝙蝠原理发明了什么",answer:"雷达",explain:"答案是：雷达。"},]},
{id:39,title:"卖火柴的小女孩",emoji:"🔥",color:"#dbeafe",level:"中级",text:"大年夜下雪,小女孩赤脚卖火柴。她蜷缩在墙角,点燃火柴取暖。第一次看到火炉,第二次看到烤鹅,第三次看到奶奶。火柴灭了,一切消失了,小女孩在寒夜中死去了。",questions:[{type:"choice",question:"小女孩在什么天气卖火柴",options:["下雪天","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：下雪天。"},{type:"fill",question:"小女孩在房子的___角坐下",answer:"墙",explain:"答案是：墙。"},{type:"choice",question:"第一次点燃火柴看到什么",options:["火炉","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：火炉。"},{type:"fill",question:"小女孩最后怎样了",answer:"在寒夜中死去",explain:"答案是：在寒夜中死去。"},]},
{id:40,title:"骆驼和羊",emoji:"🐫",color:"#dbeafe",level:"中级",text:"骆驼说高好,羊说矮好。骆驼在园子旁抬头吃到树叶,羊够不着。走到窄小门前,羊钻进去吃草,骆驼钻不进去。老牛说:只看到自己长处看不到短处是不对的。",questions:[{type:"choice",question:"骆驼认为什么好",options:["长得高好","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：长得高好。"},{type:"fill",question:"羊走进了一个___的门",answer:"窄小",explain:"答案是：窄小。"},{type:"choice",question:"骆驼在园子旁吃到什么",options:["树叶","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：树叶。"},{type:"fill",question:"老牛的话告诉我们什么",answer:"要看别人长处也要看自己短处",explain:"答案是：要看别人长处也要看自己短处。"},]},
{id:41,title:"钱学森",emoji:"🚀",color:"#dbeafe",level:"中级",text:"钱学森在美国成绩优秀。新中国成立后想回国,美国人说他一个人能顶五个师,软禁了他五年。一九五五年终于回国,领导研制了导弹和火箭,被称为中国航天之父。",questions:[{type:"choice",question:"钱学森在哪里学习",options:["美国","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：美国。"},{type:"fill",question:"美国人说他能顶___个师",answer:"五",explain:"答案是：五。"},{type:"choice",question:"被软禁了几年",options:["五年","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：五年。"},{type:"fill",question:"被称为中国什么之父",answer:"航天",explain:"答案是：航天。"},]},
{id:42,title:"盲人摸象",emoji:"🐘",color:"#dbeafe",level:"中级",text:"四个盲人摸大象。第一个摸牙齿说像萝卜,第二个摸耳朵说像扇子,第三个摸腿说像柱子,第四个摸尾巴说像绳子。其实都只摸到一部分,看问题不能以偏概全。",questions:[{type:"choice",question:"第一个盲人摸到大象的什么",options:["牙齿","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：牙齿。"},{type:"fill",question:"摸到耳朵的说像一把___",answer:"扇子",explain:"答案是：扇子。"},{type:"choice",question:"摸到腿的说像什么",options:["柱子","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：柱子。"},{type:"fill",question:"故事告诉我们什么",answer:"看问题要全面不能以偏概全",explain:"答案是：看问题要全面不能以偏概全。"},]},
{id:43,title:"荷叶上的珍珠",emoji:"🪷",color:"#dbeafe",level:"中级",text:"清晨荷叶上有水珠像珍珠。碰一下水珠滚到一起变大,荷叶不湿。原来荷叶表面有细小突起,水无法铺开。科学家模仿荷叶发明了防水衣服和防污涂料。",questions:[{type:"choice",question:"荷叶上水珠像什么",options:["珍珠","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：珍珠。"},{type:"fill",question:"荷叶表面有细小___",answer:"突起",explain:"答案是：突起。"},{type:"choice",question:"荷叶为什么不湿",options:["表面有突起水无法铺开","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：表面有突起水无法铺开。"},{type:"fill",question:"科学家模仿荷叶发明了什么",answer:"防水衣服和防污涂料",explain:"答案是：防水衣服和防污涂料。"},]},
{id:44,title:"孔子学琴",emoji:"🎻",color:"#dbeafe",level:"中级",text:"孔子向师襄子学琴。弹了十天师襄子说可学新曲了,孔子说还没掌握技巧。过了些日子说可学新的了,孔子说还没领会意境。终于从琴声看到作曲者模样,说是周文王。师襄子说这正是《文王操》。",questions:[{type:"choice",question:"孔子向谁学琴",options:["师襄子","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：师襄子。"},{type:"fill",question:"孔子说还没掌握___",answer:"技巧",explain:"答案是：技巧。"},{type:"choice",question:"从琴声看到谁的模样",options:["周文王","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：周文王。"},{type:"fill",question:"体现孔子什么品质",answer:"谦虚好学精益求精",explain:"答案是：谦虚好学精益求精。"},]},
{id:45,title:"狼来了",emoji:"🐺",color:"#dbeafe",level:"中级",text:"放羊孩子无聊喊狼来了,村民跑来发现被骗。第二天又喊又被骗。第三天狼真来了,没人来救,羊被吃了好几只。说谎的人会失去别人的信任。",questions:[{type:"choice",question:"第一次喊狼来了时狼来了吗",options:["没来","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：没来。"},{type:"fill",question:"孩子喊狼来了是为了___",answer:"好玩",explain:"答案是：好玩。"},{type:"choice",question:"第三次为什么没人来",options:["以为他又在撒谎","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：以为他又在撒谎。"},{type:"fill",question:"故事告诉我们什么",answer:"说谎的人会失去别人的信任",explain:"答案是：说谎的人会失去别人的信任。"},]},
{id:46,title:"海底世界",emoji:"🐠",color:"#dbeafe",level:"中级",text:"海面波涛澎湃时海底依然宁静。海底有发光生物。海参靠肌肉伸缩一小时走四米,梭子鱼每小时游几十千米,乌贼章鱼利用水的反推力后退,贝类巴在船底旅行。",questions:[{type:"choice",question:"海面波涛时海底怎样",options:["依然宁静","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：依然宁静。"},{type:"fill",question:"海参靠肌肉___爬行",answer:"伸缩",explain:"答案是：伸缩。"},{type:"choice",question:"哪种动物游最快",options:["梭子鱼","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：梭子鱼。"},{type:"fill",question:"乌贼章鱼怎么活动",answer:"利用水的反推力后退",explain:"答案是：利用水的反推力后退。"},]},
{id:47,title:"难忘的一课",emoji:"📖",color:"#dbeafe",level:"中级",text:"李老师拿苹果问我们看到了什么。大家说一个苹果。小刚说有小斑点,小红说一边红一边绿。老师说同一苹果每个人看到的都不同,写作文要学会仔细观察从不同角度看事物。",questions:[{type:"choice",question:"老师拿什么进教室",options:["一个苹果","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一个苹果。"},{type:"fill",question:"小刚说苹果有 小___",answer:"斑点",explain:"答案是：斑点。"},{type:"choice",question:"小红观察苹果怎样",options:["一边红一边绿","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一边红一边绿。"},{type:"fill",question:"老师想告诉我们什么",answer:"学会仔细观察从不同角度看事物",explain:"答案是：学会仔细观察从不同角度看事物。"},]},
{id:48,title:"花钟",emoji:"🕰️",color:"#dbeafe",level:"中级",text:"不同的花开放时间不同。凌晨四点牵牛花开,五点蔷薇开,七点睡莲开,中午午时花开,下午三点万寿菊开,傍晚烟草花开。植物学家据此组成了花钟,看什么花开就知道几点。",questions:[{type:"choice",question:"牵牛花几点开",options:["凌晨四点","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：凌晨四点。"},{type:"fill",question:"睡莲从___中醒来",answer:"梦",explain:"答案是：梦。"},{type:"choice",question:"万寿菊什么时候开",options:["下午三点","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：下午三点。"},{type:"fill",question:"花钟根据什么原理制作",answer:"不同花开放时间不同",explain:"答案是：不同花开放时间不同。"},]},
{id:49,title:"井底之蛙",emoji:"🐸",color:"#dbeafe",level:"中级",text:"青蛙住井里觉得最舒适,看到的天只有井口大。海龟说大海大得看不到边。青蛙惊讶地张大嘴,明白外面世界比想象的大得多。看问题不要目光短浅。",questions:[{type:"choice",question:"青蛙住在哪里",options:["井里","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：井里。"},{type:"fill",question:"青蛙看到的天只有___大",answer:"井口",explain:"答案是：井口。"},{type:"choice",question:"谁告诉青蛙大海的事",options:["海龟","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：海龟。"},{type:"fill",question:"井底之蛙告诉我们什么",answer:"不要目光短浅要开阔视野",explain:"答案是：不要目光短浅要开阔视野。"},]},
{id:50,title:"聪明的乌鸦",emoji:"🐦‍⬛",color:"#dbeafe",level:"中级",text:"路人喝不到瓶中水。一只乌鸦衔石子往瓶里扔,水位升高,乌鸦喝到了水。它说看到石子沉下去水会上升就试了试。遇到问题多观察多思考就能找到办法。",questions:[{type:"choice",question:"谁想出了喝水办法",options:["一只乌鸦","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一只乌鸦。"},{type:"fill",question:"乌鸦把___往瓶里扔",answer:"石子",explain:"答案是：石子。"},{type:"choice",question:"怎么想到这办法",options:["看到石子沉水会上升","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：看到石子沉水会上升。"},{type:"fill",question:"告诉我们什么",answer:"多观察多思考就能找到办法",explain:"答案是：多观察多思考就能找到办法。"},]},
{id:51,title:"长城",emoji:"🧱",color:"#dbeafe",level:"中级",text:"长城从山海关到嘉峪关,全长六千多公里。秦始皇下令修建,后经历代修缮。烽火台传递军情。长城是劳动人民智慧的结晶,也是世界文化遗产。",questions:[{type:"choice",question:"长城从哪到哪",options:["山海关到嘉峪关","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：山海关到嘉峪关。"},{type:"fill",question:"长城全长___多公里",answer:"六千",explain:"答案是：六千。"},{type:"choice",question:"烽火台用来做什么",options:["传递军情","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：传递军情。"},{type:"fill",question:"长城谁下令修建",answer:"秦始皇",explain:"答案是：秦始皇。"},]},
{id:52,title:"画蛇添足",emoji:"🐍",color:"#dbeafe",level:"中级",text:"几个人争一壶酒,比画蛇谁先画完谁喝。最快的人画好了又给蛇画脚。另一个人画完抢过酒说蛇没有脚,你画的不是蛇了。做事不要多此一举。",questions:[{type:"choice",question:"几人争一壶什么",options:["酒","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：酒。"},{type:"fill",question:"画最快的人给蛇画上了___",answer:"脚",explain:"答案是：脚。"},{type:"choice",question:"最后谁喝到酒",options:["另一个画完的人","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：另一个画完的人。"},{type:"fill",question:"告诉我们什么",answer:"做事不要多此一举",explain:"答案是：做事不要多此一举。"},]},
{id:53,title:"蜜蜂和蝴蝶",emoji:"🐝",color:"#dbeafe",level:"中级",text:"春天蜜蜂忙着采蜜,蝴蝶在一旁玩耍。蝴蝶嘲笑蜜蜂傻。冬天来了,蜜蜂在蜂巢吃蜂蜜,蝴蝶又冷又饿冻死了。只有辛勤劳动才能换来幸福生活。",questions:[{type:"choice",question:"春天蝴蝶在做什么",options:["玩耍","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：玩耍。"},{type:"fill",question:"蝴蝶嘲笑蜜蜂真___",answer:"傻",explain:"答案是：傻。"},{type:"choice",question:"冬天蜜蜂吃什么",options:["蜂蜜","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：蜂蜜。"},{type:"fill",question:"告诉我们什么",answer:"只有辛勤劳动才能换来幸福生活",explain:"答案是：只有辛勤劳动才能换来幸福生活。"},]},
{id:54,title:"竹子",emoji:"🎋",color:"#dbeafe",level:"中级",text:"竹子常绿,最高可长到二十多米。竹笋一天能长高一米多。竹子中间是空的,一节一节,轻但结实。可做筷子竹篮竹席造纸。竹子象征正直和坚强。",questions:[{type:"choice",question:"竹子最高长到多少",options:["二十多米","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：二十多米。"},{type:"fill",question:"竹子中间是___的",answer:"空",explain:"答案是：空。"},{type:"choice",question:"竹笋一天能长高多少",options:["一米多","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一米多。"},{type:"fill",question:"竹子象征什么",answer:"正直和坚强",explain:"答案是：正直和坚强。"},]},
{id:55,title:"赠汪伦",emoji:"📜",color:"#dbeafe",level:"中级",text:"李白《赠汪伦》:李白乘舟将欲行,忽闻岸上踏歌声。桃花潭水深千尺,不及汪伦送我情。汪伦在岸边边走边唱歌为李白送行。用桃花潭水比喻友情。",questions:[{type:"choice",question:"作者是谁",options:["李白","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：李白。"},{type:"fill",question:"汪伦边走边___",answer:"唱歌",explain:"答案是：唱歌。"},{type:"choice",question:"诗中用什么比喻友情",options:["桃花潭的水","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：桃花潭的水。"},{type:"fill",question:"诗表达什么感情",answer:"朋友间深厚友情",explain:"答案是：朋友间深厚友情。"},]},
{id:56,title:"小草",emoji:"🌿",color:"#dbeafe",level:"中级",text:"有人喜欢牡丹莲花,我喜欢小草。小草生命力顽强,古诗说野火烧不尽春风吹又生。小草还能保护水土不让泥土流失。它不需要人浇水施肥却默默守护大地。",questions:[{type:"choice",question:"作者喜欢什么植物",options:["小草","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：小草。"},{type:"fill",question:"一岁一枯___",answer:"荣",explain:"答案是：荣。"},{type:"choice",question:"小草有什么品质",options:["生命力极其顽强","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：生命力极其顽强。"},{type:"fill",question:"小草还有什么作用",answer:"保护水土不让流失",explain:"答案是：保护水土不让流失。"},]},
{id:57,title:"狐狸和葡萄",emoji:"🦊",color:"#dbeafe",level:"中级",text:"狐狸饿了看到葡萄架上紫红葡萄。跳了好多没摘到,累得满头大汗。放弃了说葡萄肯定是酸的不好吃。自己得不到的东西就说那东西不好。",questions:[{type:"choice",question:"狐狸想吃什么",options:["葡萄","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：葡萄。"},{type:"fill",question:"狐狸累得满头大___",answer:"汗",explain:"答案是：汗。"},{type:"choice",question:"狐狸最后怎样",options:["放弃了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：放弃了。"},{type:"fill",question:"故事讽刺什么人",answer:"自己得不到就说东西不好的人",explain:"答案是：自己得不到就说东西不好的人。"},]},
{id:58,title:"指南针",emoji:"🧭",color:"#dbeafe",level:"中级",text:"指南针是四大发明之一,一端指南一端指北。因为地球本身是磁铁,磁铁同极相斥异极相吸。有了指南针航海不迷失方向。之前人们靠看星星辨别方向。",questions:[{type:"choice",question:"指南针是什么之一",options:["四大发明","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：四大发明。"},{type:"fill",question:"地球本身就是一个大___",answer:"磁铁",explain:"答案是：磁铁。"},{type:"choice",question:"为什么能指南北",options:["地球是磁铁同极相斥异极相吸","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：地球是磁铁同极相斥异极相吸。"},{type:"fill",question:"之前靠什么辨别方向",answer:"看星星",explain:"答案是：看星星。"},]},
{id:59,title:"春联",emoji:"🧧",color:"#dbeafe",level:"中级",text:"春节家家贴红春联,写吉祥话语寄托美好愿望。上联贴右边下联贴左边,中间贴横批。字数要一样词性要相对平仄要相配。读春联写春联是传统文化。",questions:[{type:"choice",question:"春联右边贴什么",options:["上联","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：上联。"},{type:"fill",question:"中间贴着___",answer:"横批",explain:"答案是：横批。"},{type:"choice",question:"写春联有什么讲究",options:["字数一样词性相对平仄相配","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：字数一样词性相对平仄相配。"},{type:"fill",question:"春联寄托什么",answer:"对新年的美好愿望",explain:"答案是：对新年的美好愿望。"},]},
{id:60,title:"精卫填海",emoji:"🐦",color:"#dbeafe",level:"中级",text:"炎帝小女儿女娃淹死后变成精卫鸟。她痛恨大海,每天从西山衔石子和树枝投进海里要填平大海。日复一日从不间断。要有坚定的信念和不屈不挠的精神。",questions:[{type:"choice",question:"精卫是谁变的",options:["女娃","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：女娃。"},{type:"fill",question:"精卫每天衔石子和___",answer:"树枝",explain:"答案是：树枝。"},{type:"choice",question:"为什么要填海",options:["大海夺走了她的生命","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：大海夺走了她的生命。"},{type:"fill",question:"告诉我们什么",answer:"要有坚定信念和不屈不挠精神",explain:"答案是：要有坚定信念和不屈不挠精神。"},]},
{id:61,title:"纸的发明",emoji:"📄",color:"#dbeafe",level:"中级",text:"纸发明前人们把字刻在竹片木片上很重。蔡伦用树皮麻头破布旧鱼网做原料,经切碎浸泡蒸煮捣烂抄纸晾干等工序造出轻薄的纸。纸方便了记录传播知识推动文明进步。",questions:[{type:"choice",question:"纸发明前字刻在哪",options:["竹片或木片上","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：竹片或木片上。"},{type:"fill",question:"谁改进了造纸术",answer:"蔡伦",explain:"答案是：蔡伦。"},{type:"choice",question:"用什么做原料",options:["树皮麻头破布旧鱼网","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：树皮麻头破布旧鱼网。"},{type:"fill",question:"纸的发明有什么意义",answer:"方便记录传播知识推动文明进步",explain:"答案是：方便记录传播知识推动文明进步。"},]},
{id:62,title:"农夫与蛇",emoji:"🐍",color:"#dbeafe",level:"中级",text:"农夫在雪地发现冻僵的蛇,放在怀里暖着。蛇恢复后不但不感谢反而咬了农夫一口。农夫中毒倒地。对恶人不能心慈手软,善良要用在对的人身上。",questions:[{type:"choice",question:"农夫发现了什么",options:["一条冻僵的蛇","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一条冻僵的蛇。"},{type:"fill",question:"农夫把蛇放在___里",answer:"怀",explain:"答案是：怀。"},{type:"choice",question:"蛇恢复后做了什么",options:["咬了农夫一口","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：咬了农夫一口。"},{type:"fill",question:"告诉我们什么",answer:"对恶人不能心慈手软",explain:"答案是：对恶人不能心慈手软。"},]},
{id:63,title:"赵州桥",emoji:"🌉",color:"#dbeafe",level:"中级",text:"赵州桥在河北赵县,石拱桥,有一千四百多年历史。全长五十多米宽约十米。大桥洞顶上各有两个小桥洞,发大水时水可从小桥洞流过减轻冲击。设计者是隋代李春。",questions:[{type:"choice",question:"赵州桥在哪里",options:["河北赵县","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：河北赵县。"},{type:"fill",question:"设计者是隋代的___",answer:"李春",explain:"答案是：李春。"},{type:"choice",question:"有多少年历史",options:["一千四百多年","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一千四百多年。"},{type:"fill",question:"小桥洞有什么用",answer:"减轻流水对桥身冲击",explain:"答案是：减轻流水对桥身冲击。"},]},
{id:64,title:"刻舟求剑",emoji:"⚔️",color:"#dbeafe",level:"中级",text:"一人坐船掉剑入水,在船舷刻记号说剑从这掉下。到岸后从刻记号处下水找剑找不到。船走了但剑不会动。解决问题要根据实际情况不能死板。",questions:[{type:"choice",question:"那人把什么掉进水里",options:["剑","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：剑。"},{type:"fill",question:"那人在船___上刻记号",answer:"舷",explain:"答案是：舷。"},{type:"choice",question:"为什么找不到剑",options:["船走了但剑不动位置变了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：船走了但剑不动位置变了。"},{type:"fill",question:"告诉我们什么",answer:"解决问题要根据实际情况不能死板",explain:"答案是：解决问题要根据实际情况不能死板。"},]},
{id:65,title:"望梅止渴",emoji:"🟢",color:"#dbeafe",level:"中级",text:"曹操带兵途中找不到水士兵渴得走不动。曹操指前方说有大片梅林梅子又酸又甜可解渴。士兵流口水觉得不渴了继续走找到水源。后来用望梅止渴比喻用空想安慰自己。",questions:[{type:"choice",question:"主人公是谁",options:["曹操","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：曹操。"},{type:"fill",question:"曹操说前面有大片___",answer:"梅林",explain:"答案是：梅林。"},{type:"choice",question:"士兵听到有梅子怎样",options:["流口水不渴了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：流口水不渴了。"},{type:"fill",question:"望梅止渴比喻什么",answer:"用空想来安慰自己",explain:"答案是：用空想来安慰自己。"},]},
{id:66,title:"黄鹤楼",emoji:"🏯",color:"#dbeafe",level:"中级",text:"黄鹤楼位于武汉蛇山,中国四大名楼之一,近两千年历史。高五层金碧辉煌。崔颢写《黄鹤楼》最有名。黄鹤楼不仅是建筑更是中华文化的象征。",questions:[{type:"choice",question:"黄鹤楼在哪里",options:["武汉蛇山","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：武汉蛇山。"},{type:"fill",question:"高___层",answer:"五",explain:"答案是：五。"},{type:"choice",question:"最有名的诗谁写的",options:["崔颢","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：崔颢。"},{type:"fill",question:"黄鹤楼是什么象征",answer:"中华文化的象征",explain:"答案是：中华文化的象征。"},]},
{id:67,title:"鲁班造锯",emoji:"🪚",color:"#dbeafe",level:"中级",text:"鲁班上山砍柴被野草割手,发现草叶边缘有小齿。想如果用铁片做带齿工具能否更快锯木头。回去试验果然又快又省力。要善于观察自然从中学习。",questions:[{type:"choice",question:"锯子谁发明的",options:["鲁班","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：鲁班。"},{type:"fill",question:"鲁班被___割破手",answer:"野草",explain:"答案是：野草。"},{type:"choice",question:"草叶边缘有什么",options:["小齿","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：小齿。"},{type:"fill",question:"告诉我们什么",answer:"要善于观察自然从中学习",explain:"答案是：要善于观察自然从中学习。"},]},
{id:68,title:"地震",emoji:"🌋",color:"#dbeafe",level:"中级",text:"地震是自然灾害,大地剧烈摇晃。地球外壳由很多板块组成,板块挤压碰撞产生地震。地震时要冷静:教室躲桌下保护头部,室外到空旷地方远离高楼电线杆。不要乘电梯不要跳楼。",questions:[{type:"choice",question:"地震是什么",options:["自然灾害","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：自然灾害。"},{type:"fill",question:"地球外壳由很多___组成",answer:"板块",explain:"答案是：板块。"},{type:"choice",question:"教室里应该怎样",options:["躲桌下保护头部","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：躲桌下保护头部。"},{type:"fill",question:"地震时不能做什么",answer:"乘电梯",explain:"答案是：乘电梯。"},]},
{id:69,title:"郑人买履",emoji:"👞",color:"#dbeafe",level:"中级",text:"郑国人买鞋先量好尺寸,到鞋铺发现忘带尺寸跑回家拿,回来集市散了没买到。别人问为何不用脚试,他说宁可相信尺寸也不信脚。做事不要墨守成规要灵活变通。",questions:[{type:"choice",question:"买鞋时忘了带什么",options:["量好的尺寸","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：量好的尺寸。"},{type:"fill",question:"回来集市已经___了",answer:"散",explain:"答案是：散。"},{type:"choice",question:"别人建议用什么试鞋",options:["自己的脚","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：自己的脚。"},{type:"fill",question:"告诉我们什么",answer:"不要墨守成规要灵活变通",explain:"答案是：不要墨守成规要灵活变通。"},]},
{id:70,title:"掩耳盗铃",emoji:"🔔",color:"#dbeafe",level:"中级",text:"有个小偷想偷一口大钟。钟太重搬不动,想敲碎再搬。一敲钟就响了,小偷怕别人听到。他想:我捂住自己的耳朵不就听不到了吗?结果当然被人发现了。自己欺骗自己,别人又不是聋子。",questions:[{type:"choice",question:"小偷想偷什么",options:["一口大钟","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：一口大钟。"},{type:"fill",question:"小偷捂住自己的___",answer:"耳朵",explain:"答案是：耳朵。"},{type:"choice",question:"小偷以为怎样",options:["捂住自己耳朵别人就听不到了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：捂住自己耳朵别人就听不到了。"},{type:"fill",question:"告诉我们什么",answer:"不要自欺欺人",explain:"答案是：不要自欺欺人。"},]},
{id:71,title:"少年中国说",emoji:"🇨🇳",color:"#e0e7ff",level:"高级",text:"梁启超《少年中国说》:少年智则国智,少年富则国富,少年强则国强。写于1900年中国积贫积弱时。他认为国家未来在于年轻人。今天我们仍要好好学习为国争光,少年强则国强是每个人的责任。",questions:[{type:"choice",question:"作者是谁",options:["梁启超","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：梁启超。"},{type:"fill",question:"少年强则国___",answer:"强",explain:"答案是：强。"},{type:"choice",question:"写于哪年",options:["1900年","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：1900年。"},{type:"fill",question:"国家未来在于谁",answer:"年轻人",explain:"答案是：年轻人。"},{type:"choice",question:"文章告诉我们什么",options:["要好好学习为国争光","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：要好好学习为国争光。"},]},
{id:72,title:"居里夫人",emoji:"⚛️",color:"#e0e7ff",level:"高级",text:"居里夫人发现镭和钋,两次获诺贝尔奖。年轻时家穷为供姐姐上学做家庭教师。在巴黎大学学习生活艰苦从不放弃。和丈夫用四年从几吨沥青铀矿提炼出零点一克纯镭。她不申请专利,说科学属于全人类。",questions:[{type:"choice",question:"她发现了什么",options:["镭和钋","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：镭和钋。"},{type:"fill",question:"___次获诺贝尔奖",answer:"两",explain:"答案是：两。"},{type:"choice",question:"为何做家庭教师",options:["供姐姐上学","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：供姐姐上学。"},{type:"fill",question:"提炼镭用了多久",answer:"四年",explain:"答案是：四年。"},{type:"choice",question:"为何不申请专利",options:["认为科学属于全人类","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：认为科学属于全人类。"},]},
{id:73,title:"愚公移山",emoji:"⛰️",color:"#e0e7ff",level:"高级",text:"愚公家门前两座大山挡路。九十岁愚公要搬走大山。智叟嘲笑他,愚公说子子孙孙无穷尽山不会长高总有一天搬完。天帝感动派大力神搬走山。有坚定信念和坚持精神就没有克服不了的困难。",questions:[{type:"choice",question:"门前几座大山",options:["两座","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：两座。"},{type:"fill",question:"愚公说山不会___",answer:"长高",explain:"答案是：长高。"},{type:"choice",question:"谁嘲笑愚公",options:["邻居智叟","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：邻居智叟。"},{type:"fill",question:"谁搬走了山",answer:"天帝派的大力神",explain:"答案是：天帝派的大力神。"},{type:"choice",question:"告诉我们什么",options:["有坚定信念和坚持就能克服困难","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：有坚定信念和坚持就能克服困难。"},]},
{id:74,title:"草船借箭",emoji:"🏹",color:"#e0e7ff",level:"高级",text:"周瑜让诸葛亮十天造十万支箭,诸葛亮说只要三天。第三天夜里江上大雾,二十条船扎满草人驶向曹军。曹操看不清虚实只放箭,箭射满草人。得箭十万余支。周瑜叹诸葛亮神机妙算。遇到困难善于动脑利用条件解决。",questions:[{type:"choice",question:"周瑜让几天造箭",options:["十天","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：十天。"},{type:"fill",question:"借箭利用了江上的大___",answer:"雾",explain:"答案是：雾。"},{type:"choice",question:"曹操为何只放箭",options:["看不清虚实","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：看不清虚实。"},{type:"fill",question:"共得多少箭",answer:"十万余支",explain:"答案是：十万余支。"},{type:"choice",question:"告诉我们什么",options:["善于动脑利用条件解决困难","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：善于动脑利用条件解决困难。"},]},
{id:75,title:"闻鸡起舞",emoji:"🐓",color:"#e0e7ff",level:"高级",text:"祖逖和刘琨是好朋友,立志报效国家。每天听到鸡叫就起床练剑,寒冬酷暑从不间断。后来祖逖成为著名将军收复大片失地。想成就事业必须有刻苦精神和坚定意志。",questions:[{type:"choice",question:"主人公是谁",options:["祖逖和刘琨","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：祖逖和刘琨。"},{type:"fill",question:"听到___叫就起床练剑",answer:"鸡",explain:"答案是：鸡。"},{type:"choice",question:"不管什么天气",options:["寒冬酷暑都不间断","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：寒冬酷暑都不间断。"},{type:"fill",question:"祖逖后来成为什么",answer:"将军",explain:"答案是：将军。"},{type:"choice",question:"告诉我们什么",options:["想成就事业必须有刻苦精神和坚定意志","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：想成就事业必须有刻苦精神和坚定意志。"},]},
{id:76,title:"铁杵磨成针",emoji:"🪡",color:"#e0e7ff",level:"高级",text:"李白小时候不爱学习经常逃学。在河边看到老奶奶磨铁棒,说要磨成绣花针。老奶奶说只要功夫深铁杵磨成针。李白深受感动从此发奋读书,成为伟大诗人。有恒心有毅力再难也能做到。",questions:[{type:"choice",question:"李白小时候怎样",options:["不爱学习经常逃学","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：不爱学习经常逃学。"},{type:"fill",question:"老奶奶在磨一根___",answer:"铁棒",explain:"答案是：铁棒。"},{type:"choice",question:"磨成什么",options:["绣花针","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：绣花针。"},{type:"fill",question:"老奶奶说了什么",answer:"只要功夫深铁杵磨成针",explain:"答案是：只要功夫深铁杵磨成针。"},{type:"choice",question:"李白后来怎样",options:["发奋读书成为伟大诗人","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：发奋读书成为伟大诗人。"},]},
{id:77,title:"负荆请罪",emoji:"🌿",color:"#e0e7ff",level:"高级",text:"廉颇嫉妒蔺相如职位高,蔺相如处处回避。手下不理解,蔺相如说秦不敢犯赵就是因为有他们两人,避让是为了国家。廉颇听说后惭愧,背荆条去请罪,两人成好友。知错能改是勇敢,以国家利益为重才是真英雄。",questions:[{type:"choice",question:"廉颇为何嫉妒",options:["蔺相如职位比他高","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：蔺相如职位比他高。"},{type:"fill",question:"蔺相如处处___廉颇",answer:"回避",explain:"答案是：回避。"},{type:"choice",question:"为何避让",options:["为了国家利益","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：为了国家利益。"},{type:"fill",question:"廉颇背着什么去请罪",answer:"荆条",explain:"答案是：荆条。"},{type:"choice",question:"告诉我们什么",options:["知错能改是勇敢表现,以国家利益为重才是英雄","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：知错能改是勇敢表现,以国家利益为重才是英雄。"},]},
{id:78,title:"夸父逐日",emoji:"☀️",color:"#e0e7ff",level:"高级",text:"夸父是巨人,想追上太阳。渴了喝黄河渭水,继续追。越来越渴,向北方大泽跑去,没走到就渴死了。手杖落在地上变成一片桃林。表现了征服自然的决心和追求理想的精神。",questions:[{type:"choice",question:"夸父想追上什么",options:["太阳","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：太阳。"},{type:"fill",question:"渴了喝黄河和___的水",answer:"渭水",explain:"答案是：渭水。"},{type:"choice",question:"最后怎样了",options:["没走到大泽就渴死了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：没走到大泽就渴死了。"},{type:"fill",question:"手杖变成什么",answer:"一片桃林",explain:"答案是：一片桃林。"},{type:"choice",question:"表现了什么精神",options:["征服自然的决心和追求理想的精神","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：征服自然的决心和追求理想的精神。"},]},
{id:79,title:"完璧归赵",emoji:"💎",color:"#e0e7ff",level:"高级",text:"赵国有和氏璧,秦王说用十五座城换。蔺相如带玉出使秦国。秦王拿玉后不提城池。蔺相如说玉有瑕疵要指给秦王看,拿回玉后说秦王不守信就撞碎玉。趁夜派人把玉偷偷送回赵国。凭借智慧和勇气保住国宝。",questions:[{type:"choice",question:"和氏璧是哪国的宝物",options:["赵国","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：赵国。"},{type:"fill",question:"秦王说用十五座___换",answer:"城",explain:"答案是：城。"},{type:"choice",question:"怎么拿回玉的",options:["说玉有瑕疵要指给秦王看","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：说玉有瑕疵要指给秦王看。"},{type:"fill",question:"最后怎么送回赵国",answer:"趁夜派人偷偷送回",explain:"答案是：趁夜派人偷偷送回。"},{type:"choice",question:"体现什么品质",options:["智慧和勇气","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：智慧和勇气。"},]},
{id:80,title:"画龙点睛",emoji:"🐉",color:"#e0e7ff",level:"高级",text:"张僧繇在安乐寺墙上画四条龙不画眼睛。说画了眼睛龙会飞走。大家不信非要他画。给两条龙画上眼睛,电闪雷鸣龙腾空飞去。做事要抓住关键在最重要的地方用功夫。",questions:[{type:"choice",question:"张僧繇在哪里画龙",options:["安乐寺","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：安乐寺。"},{type:"fill",question:"画了___条龙",answer:"四",explain:"答案是：四。"},{type:"choice",question:"画上眼睛后怎样",options:["两条龙飞走了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：两条龙飞走了。"},{type:"fill",question:"为何不画眼睛",answer:"说画了龙会飞走",explain:"答案是：说画了龙会飞走。"},{type:"choice",question:"告诉我们什么",options:["做事要抓住关键","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：做事要抓住关键。"},]},
{id:81,title:"卧薪尝胆",emoji:"🗡️",color:"#e0e7ff",level:"高级",text:"越王勾践被吴国打败成俘虏,受尽屈辱三年后回国。发誓报仇,每天睡柴草,饭前舔苦胆提醒不忘耻辱。亲自下田耕种与百姓同甘共苦。十年后越国强大打败吴国。失败不可怕,可怕的是失去斗志。",questions:[{type:"choice",question:"勾践被哪国打败",options:["吴国","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：吴国。"},{type:"fill",question:"每天睡在___上",answer:"柴草",explain:"答案是：柴草。"},{type:"choice",question:"每天舔什么提醒自己",options:["苦胆","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：苦胆。"},{type:"fill",question:"在吴国当了几年俘虏",answer:"三年",explain:"答案是：三年。"},{type:"choice",question:"告诉我们什么",options:["失败不可怕可怕的是失去斗志","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：失败不可怕可怕的是失去斗志。"},]},
{id:82,title:"孟母三迁",emoji:"🏠",color:"#e0e7ff",level:"高级",text:"孟子家住墓地旁,模仿哭丧。孟母搬到集市旁,孟子模仿叫卖。又搬到学堂旁,孟子模仿读书变得有礼貌。孟母说这才是该住的地方。环境对人的成长影响很大,要选择好的环境。",questions:[{type:"choice",question:"最初住什么旁边",options:["墓地","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：墓地。"},{type:"fill",question:"第___次搬到学堂旁",answer:"三",explain:"答案是：三。"},{type:"choice",question:"住集市旁模仿什么",options:["商人吆喝叫卖","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：商人吆喝叫卖。"},{type:"fill",question:"搬到学堂旁后怎样",answer:"模仿读书变得有礼貌",explain:"答案是：模仿读书变得有礼貌。"},{type:"choice",question:"告诉我们什么",options:["环境对人的成长影响很大","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：环境对人的成长影响很大。"},]},
{id:83,title:"揠苗助长",emoji:"🌱",color:"#e0e7ff",level:"高级",text:"农夫嫌禾苗长得慢,把每棵禾苗往上拔高一点。累得腰酸背痛但很高兴。儿子跑到田里一看禾苗全枯死了。事物有发展规律,急于求成反而弄糟。",questions:[{type:"choice",question:"农夫觉得禾苗长得怎样",options:["太慢了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：太慢了。"},{type:"fill",question:"把每棵禾苗往上___",answer:"拔",explain:"答案是：拔。"},{type:"choice",question:"禾苗最后怎样",options:["全枯死了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：全枯死了。"},{type:"fill",question:"农夫累得怎样",answer:"腰酸背痛",explain:"答案是：腰酸背痛。"},{type:"choice",question:"告诉我们什么",options:["事物有发展规律急于求成反而弄糟","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：事物有发展规律急于求成反而弄糟。"},]},
{id:84,title:"东郭先生和狼",emoji:"🐺",color:"#e0e7ff",level:"高级",text:"东郭先生把被追的狼藏进口袋。猎人走后狼说饿要吃他。来了老农说不信狼能装进口袋,让狼再钻进去。狼钻进后老农扎紧口袋打死了狼。对恶人不能心慈手软,善良不能给错人。",questions:[{type:"choice",question:"东郭先生把什么藏进口袋",options:["狼","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：狼。"},{type:"fill",question:"狼出来后要做什么",answer:"吃东郭先生",explain:"答案是：吃东郭先生。"},{type:"choice",question:"谁帮了东郭先生",options:["老农","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：老农。"},{type:"fill",question:"老农怎么做的",answer:"让狼再钻进去然后打死",explain:"答案是：让狼再钻进去然后打死。"},{type:"choice",question:"告诉我们什么",options:["对恶人不能心慈手软","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：对恶人不能心慈手软。"},]},
{id:85,title:"三顾茅庐",emoji:"🏡",color:"#e0e7ff",level:"高级",text:"刘备想请诸葛亮出山相助。第一次去茅庐诸葛亮不在。第二次去又不在。第三次去时诸葛亮在睡觉,刘备在门外等了很久。诸葛亮被刘备的诚意感动,答应出山。诚心诚意终会打动人。",questions:[{type:"choice",question:"刘备想请谁出山",options:["诸葛亮","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：诸葛亮。"},{type:"fill",question:"去了几次",answer:"三次",explain:"答案是：三次。"},{type:"choice",question:"第三次去时诸葛亮在做什么",options:["睡觉","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：睡觉。"},{type:"fill",question:"刘备在门外做什么",answer:"等了很久",explain:"答案是：等了很久。"},{type:"choice",question:"告诉我们什么",options:["诚心诚意终会打动人","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：诚心诚意终会打动人。"},]},
{id:86,title:"守株待兔",emoji:"🐇",color:"#e0e7ff",level:"高级",text:"农夫在田里干活,一只兔子撞死在树桩上。农夫白捡了兔子很高兴,从此不干活了,天天守在树桩旁等兔子。结果再也没等到兔子,田地荒了。不能心存侥幸,要靠自己努力。",questions:[{type:"choice",question:"兔子撞死在哪里",options:["树桩上","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：树桩上。"},{type:"fill",question:"农夫之后做什么",answer:"天天守在树桩旁等兔子",explain:"答案是：天天守在树桩旁等兔子。"},{type:"choice",question:"结果怎样",options:["再也没等到田地荒了","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：再也没等到田地荒了。"},{type:"fill",question:"告诉我们什么",answer:"不能心存侥幸要靠自己努力",explain:"答案是：不能心存侥幸要靠自己努力。"},]},
{id:87,title:"塞翁失马",emoji:"🐎",color:"#e0e7ff",level:"高级",text:"塞翁丢了马,别人安慰他,他说焉知非福。不久马带了一匹骏马回来。别人祝贺,他说焉知非祸。儿子骑马摔断了腿,别人安慰,他说焉知非福。后来打仗儿子因腿伤没被征兵保住了命。坏事和好事可以互相转化。",questions:[{type:"choice",question:"塞翁丢了什么",options:["马","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：马。"},{type:"fill",question:"马带了什么回来",answer:"一匹骏马",explain:"答案是：一匹骏马。"},{type:"choice",question:"儿子怎么了",options:["骑马摔断了腿","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：骑马摔断了腿。"},{type:"fill",question:"儿子因腿伤怎样",answer:"没被征兵保住了命",explain:"答案是：没被征兵保住了命。"},{type:"choice",question:"告诉我们什么",options:["坏事和好事可以互相转化","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：坏事和好事可以互相转化。"},]},
{id:88,title:"南辕北辙",emoji:"🚗",color:"#e0e7ff",level:"高级",text:"有人要去南方的楚国,却驾车往北走。朋友说方向反了,他说马好。朋友说马好也没用,他说路费多。朋友说路费多也没用,他说车夫技术好。方向错了条件越好离目标越远。做事要选对方向。",questions:[{type:"choice",question:"那人要去哪里",options:["楚国","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：楚国。"},{type:"fill",question:"他往哪个方向走",answer:"北",explain:"答案是：北。"},{type:"choice",question:"朋友说方向反了他说什么",options:["马好","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：马好。"},{type:"fill",question:"方向错了会怎样",answer:"条件越好离目标越远",explain:"答案是：条件越好离目标越远。"},{type:"choice",question:"告诉我们什么",options:["做事要选对方向","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：做事要选对方向。"},]},
{id:89,title:"程门立雪",emoji:"❄️",color:"#e0e7ff",level:"高级",text:"杨时向程颐请教问题。到程颐家时程颐正在睡觉。杨时不想打扰老师,站在门外等候。天下起了大雪,雪积了一尺多厚他还在等。程颐醒来看到非常感动。尊师重道是中华民族的传统美德。",questions:[{type:"choice",question:"杨时向谁请教",options:["程颐","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：程颐。"},{type:"fill",question:"程颐在做什么",answer:"睡觉",explain:"答案是：睡觉。"},{type:"choice",question:"杨时怎么做",options:["站在门外等候","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：站在门外等候。"},{type:"fill",question:"天下了什么",answer:"大雪",explain:"答案是：大雪。"},{type:"choice",question:"告诉我们什么",options:["尊师重道是传统美德","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：尊师重道是传统美德。"},]},
{id:90,title:"伯牙绝弦",emoji:"🎵",color:"#e0e7ff",level:"高级",text:"伯牙善于弹琴,钟子期善于听琴。伯牙弹琴想表达高山,钟子期说巍峨如泰山。伯牙想表达流水,钟子期说荡荡如江河。后来钟子期死了,伯牙摔破琴再也不弹了,因为世上再无知音。知音难觅要珍惜友谊。",questions:[{type:"choice",question:"伯牙善于什么",options:["弹琴","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：弹琴。"},{type:"fill",question:"钟子期善于什么",answer:"听琴",explain:"答案是：听琴。"},{type:"choice",question:"钟子期死后伯牙怎样",options:["摔破琴再也不弹","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：摔破琴再也不弹。"},{type:"fill",question:"为什么",answer:"世上再无知音",explain:"答案是：世上再无知音。"},{type:"choice",question:"告诉我们什么",options:["知音难觅要珍惜友谊","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：知音难觅要珍惜友谊。"},]},
{id:91,title:"破釜沉舟",emoji:"🔥",color:"#e0e7ff",level:"高级",text:"项羽带兵渡河后,下令把船凿沉,把锅打破,只带三天干粮。士兵们知道没有退路,个个奋勇杀敌,以少胜多打败了强大的秦军。下定决心不留退路,就能激发最大的勇气。",questions:[{type:"choice",question:"谁下令破釜沉舟",options:["项羽","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：项羽。"},{type:"fill",question:"把什么凿沉",answer:"船",explain:"答案是：船。"},{type:"choice",question:"把什么打破",options:["锅","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：锅。"},{type:"fill",question:"为什么这样做",answer:"让士兵没有退路奋勇杀敌",explain:"答案是：让士兵没有退路奋勇杀敌。"},{type:"choice",question:"告诉我们什么",options:["下定决心不留退路能激发最大勇气","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：下定决心不留退路能激发最大勇气。"},]},
{id:92,title:"老马识途",emoji:"🐴",color:"#e0e7ff",level:"高级",text:"齐桓公带兵出征,回来时迷了路。管仲说老马认识路,让老马走在前面。老马果然带着队伍找到了回去的路。有经验的人能起到指路的作用,要善于向有经验的人学习。",questions:[{type:"choice",question:"谁带兵迷了路",options:["齐桓公","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：齐桓公。"},{type:"fill",question:"谁出了主意",answer:"管仲",explain:"答案是：管仲。"},{type:"choice",question:"用什么找路",options:["老马","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：老马。"},{type:"fill",question:"老马怎样",answer:"带着队伍找到了回去的路",explain:"答案是：带着队伍找到了回去的路。"},{type:"choice",question:"告诉我们什么",options:["要善于向有经验的人学习","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：要善于向有经验的人学习。"},]},
{id:93,title:"磨杵成针",emoji:"🔨",color:"#e0e7ff",level:"高级",text:"唐代诗人李白小时候不爱读书。一天在溪边看到老妪磨铁杵,问做什么。老妪说磨成针。李白问能成吗。老妪说只要功夫深铁杵磨成针。李白从此发奋读书成为大诗人。做事贵在有恒心。",questions:[{type:"choice",question:"李白小时候怎样",options:["不爱读书","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：不爱读书。"},{type:"fill",question:"老妪在磨什么",answer:"铁杵",explain:"答案是：铁杵。"},{type:"choice",question:"磨成什么",options:["针","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：针。"},{type:"fill",question:"老妪说了什么",answer:"只要功夫深铁杵磨成针",explain:"答案是：只要功夫深铁杵磨成针。"},{type:"choice",question:"告诉我们什么",options:["做事贵在有恒心","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：做事贵在有恒心。"},]},
{id:94,title:"望洋兴叹",emoji:"🌊",color:"#e0e7ff",level:"高级",text:"黄河之神河伯以为自己很大很了不起。顺流而下到了北海,看到大海无边无际,感叹自己渺小。北海之神说:井底之蛙不知大海,夏天的虫子不知冰雪。见识越少越容易自满,要不断开阔眼界。",questions:[{type:"choice",question:"河伯以为谁很大",options:["自己","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：自己。"},{type:"fill",question:"到了哪里看到无边无际",answer:"北海",explain:"答案是：北海。"},{type:"choice",question:"河伯感叹什么",options:["自己渺小","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：自己渺小。"},{type:"fill",question:"北海之神怎么说的",answer:"井底之蛙不知大海",explain:"答案是：井底之蛙不知大海。"},{type:"choice",question:"告诉我们什么",options:["要不断开阔眼界不要自满","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：要不断开阔眼界不要自满。"},]},
{id:95,title:"田忌赛马",emoji:"🐎",color:"#e0e7ff",level:"高级",text:"田忌和齐王赛马。齐王的马比田忌的稍好。孙膑出了个主意:用下等马对齐王的上等马,输;用上等马对齐王的中等马,赢;用中等马对齐王的下等马,赢。三局两胜,田忌赢了齐王。善于运用策略,扬长避短,就能以弱胜强。",questions:[{type:"choice",question:"田忌和谁赛马",options:["齐王","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：齐王。"},{type:"fill",question:"谁出了赛马主意",answer:"孙膑",explain:"答案是：孙膑。"},{type:"choice",question:"用下等马对齐王的什么马",options:["上等马","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：上等马。"},{type:"fill",question:"告诉我们什么",answer:"善于运用策略扬长避短就能以弱胜强",explain:"答案是：善于运用策略扬长避短就能以弱胜强。"}]},
{id:96,title:"叶公好龙",emoji:"🐲",color:"#e0e7ff",level:"高级",text:"叶公说他最喜欢龙。家里到处画着龙雕着龙。天上的真龙听说了,下来拜访。龙头探进窗户,尾巴拖在堂上。叶公吓得魂飞魄散转身就跑。原来他喜欢的是像龙的假龙,不是真龙。嘴上说喜欢,实际行动却不是那么回事。",questions:[{type:"choice",question:"叶公说他喜欢什么",options:["龙","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：龙。"},{type:"fill",question:"真龙来了叶公怎样",answer:"吓得跑了",explain:"答案是：吓得跑了。"},{type:"choice",question:"叶公真喜欢龙吗",options:["不是喜欢的是像龙的假龙","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：不是喜欢的是像龙的假龙。"},{type:"fill",question:"告诉我们什么",answer:"不要只嘴上说喜欢而实际行动不符",explain:"答案是：不要只嘴上说喜欢而实际行动不符。"},]},
{id:97,title:"朝三暮四",emoji:"🐒",color:"#e0e7ff",level:"高级",text:"养猴人对猴子说早上给三个橡子晚上给四个。猴子们都很生气。养猴人改说早上四个晚上三个,猴子们都高兴了。其实总数一样,只是换了说法。看问题要看本质,不要被表面现象迷惑。",questions:[{type:"choice",question:"养猴人先说早上给几个",options:["三个","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：三个。"},{type:"fill",question:"猴子们怎样",answer:"很生气",explain:"答案是：很生气。"},{type:"choice",question:"改成早上几个",options:["四个","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：四个。"},{type:"fill",question:"猴子们怎样",answer:"高兴了",explain:"答案是：高兴了。"},{type:"choice",question:"告诉我们什么",options:["看问题要看本质不要被表面迷惑","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：看问题要看本质不要被表面迷惑。"},]},
{id:98,title:"画蛇添足",emoji:"🐍",color:"#e0e7ff",level:"高级",text:"几个人画蛇争酒。一人先画好,得意地给蛇添上脚。另一人画完抢酒说蛇本无脚你画的不是蛇。有时多此一举反而把事情弄糟,做事要恰到好处不要画蛇添足。",questions:[{type:"choice",question:"几人争一壶什么",options:["酒","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：酒。"},{type:"fill",question:"先画好的人给蛇添了什么",answer:"脚",explain:"答案是：脚。"},{type:"choice",question:"另一人怎么说",options:["蛇没有脚你画的不是蛇","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：蛇没有脚你画的不是蛇。"},{type:"fill",question:"告诉我们什么",answer:"做事要恰到好处不要画蛇添足",explain:"答案是：做事要恰到好处不要画蛇添足。"},]},
{id:99,title:"杯弓蛇影",emoji:"🍷",color:"#e0e7ff",level:"高级",text:"乐广请朋友喝酒。朋友看到杯中似有蛇,勉强喝下,回家就病了。乐广发现墙上弓的影子映在杯中像蛇。再请朋友来,说明真相,朋友的病就好了。疑心太重会自己吓自己,要弄清真相不要疑神疑鬼。",questions:[{type:"choice",question:"朋友在杯中看到什么",options:["似有蛇","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：似有蛇。"},{type:"fill",question:"朋友回家怎样",answer:"病了",explain:"答案是：病了。"},{type:"choice",question:"真相是什么",options:["墙上弓的影子映在杯中","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：墙上弓的影子映在杯中。"},{type:"fill",question:"知道真相后怎样",answer:"病就好了",explain:"答案是：病就好了。"},{type:"choice",question:"告诉我们什么",options:["不要疑神疑鬼要弄清真相","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：不要疑神疑鬼要弄清真相。"},]},
{id:100,title:"狐假虎威",emoji:"🦊",color:"#e0e7ff",level:"高级",text:"老虎抓住狐狸要吃它。狐狸说:你不敢吃我,老天派我做百兽之王,不信跟我走一趟。老虎跟着狐狸走,动物们看到老虎吓得跑了。老虎以为动物们怕狐狸,其实怕的是老虎。有些人借别人的威风来吓唬人。",questions:[{type:"choice",question:"谁抓住了狐狸",options:["老虎","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：老虎。"},{type:"fill",question:"狐狸说谁派它做百兽之王",answer:"老天",explain:"答案是：老天。"},{type:"choice",question:"动物们为什么跑",options:["怕老虎","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：怕老虎。"},{type:"fill",question:"老虎以为动物们怕谁",answer:"狐狸",explain:"答案是：狐狸。"},{type:"choice",question:"告诉我们什么",options:["有些人借别人威风吓唬人","错误选项1","错误选项2","错误选项3"],answer:0,explain:"答案是：有些人借别人威风吓唬人。"}
]}
];