// ===== 成语接龙数据（100组） =====
const idiomChain = [
    { idiom: "一心一意", next: "意气风发" },
    { idiom: "发扬光大", next: "大显身手" },
    { idiom: "手到擒来", next: "来日方长" },
    { idiom: "长年累月", next: "月明星稀" },
    { idiom: "齐心协力", next: "力争上游" },
    { idiom: "游刃有余", next: "余音绕梁" },
    { idiom: "画蛇添足", next: "足智多谋" },
    { idiom: "谋事在人", next: "人山人海" },
    { idiom: "海阔天空", next: "空前绝后" },
    { idiom: "后来居上", next: "上下一心" },
    { idiom: "心想事成", next: "成竹在胸" },
    { idiom: "胸有成竹", next: "竹报平安" },
    { idiom: "安步当车", next: "车水马龙" },
    { idiom: "龙飞凤舞", next: "舞文弄墨" },
    { idiom: "马到成功", next: "功德无量" },
    { idiom: "量力而行", next: "行云流水" },
    { idiom: "水落石出", next: "出生入死" },
    { idiom: "死里逃生", next: "生机勃勃" },
    { idiom: "勃然变色", next: "色厉内荏" },
    { idiom: "持之以恒", next: "恒河沙数" },
    { idiom: "兵不血刃", next: "刃迎缕解" },
    { idiom: "见义勇为", next: "为所欲为" },
    { idiom: "为人师表", next: "表里如一" },
    { idiom: "一模一样", next: "样样精通" },
    { idiom: "通情达理", next: "理直气壮" },
    { idiom: "壮志凌云", next: "云开见日" },
    { idiom: "日积月累", next: "累卵之危" },
    { idiom: "危在旦夕", next: "夕阳西下" },
    { idiom: "下笔成章", next: "章台杨柳" },
    { idiom: "柳暗花明", next: "明辨是非" },
    { idiom: "非同小可", next: "可有可无" },
    { idiom: "无中生有", next: "有口皆碑" },
    { idiom: "卑鄙无耻", next: "耻居人下" },
    { idiom: "下里巴人", next: "人面兽心" },
    { idiom: "心花怒放", next: "放虎归山" },
    { idiom: "山清水秀", next: "秀外慧中" },
    { idiom: "中流砥柱", next: "柱石之坚" },
    { idiom: "坚不可摧", next: "摧枯拉朽" },
    { idiom: "机不可失", next: "失而复得" },
    { idiom: "得不偿失", next: "失魂落魄" },
    { idiom: "魄散魂飞", next: "飞蛾扑火" },
    { idiom: "火烧眉毛", next: "毛遂自荐" },
    { idiom: "见多识广", next: "广开言路" },
    { idiom: "路不拾遗", next: "遗臭万年" },
    { idiom: "年富力强", next: "强词夺理" },
    { idiom: "理屈词穷", next: "穷山恶水" },
    { idiom: "水到渠成", next: "成人之美" },
    { idiom: "美中不足", next: "足不出户" },
    { idiom: "小题大做", next: "做贼心虚" },
    { idiom: "虚怀若谷", next: "谷马砺兵" },
    { idiom: "兵贵神速", next: "速战速决" },
    { idiom: "决一雌雄", next: "雄心壮志" },
    { idiom: "志同道合", next: "合二为一" },
    { idiom: "一丝不苟", next: "苟且偷生" },
    { idiom: "生龙活虎", next: "虎头蛇尾" },
    { idiom: "尾大不掉", next: "掉以轻心" },
    { idiom: "心安理得", next: "得心应手" },
    { idiom: "手忙脚乱", next: "乱七八糟" },
    { idiom: "糟糠之妻", next: "妻离子散" },
    { idiom: "散兵游勇", next: "勇往直前" },
    { idiom: "前呼后拥", next: "拥书百城" },
    { idiom: "城狐社鼠", next: "鼠目寸光" },
    { idiom: "光明磊落", next: "落井下石" },
    { idiom: "石破天惊", next: "惊天动地" },
    { idiom: "地动山摇", next: "摇头晃脑" },
    { idiom: "脑满肠肥", next: "肥马轻裘" },
    { idiom: "裘弊金尽", next: "尽善尽美" },
    { idiom: "美不胜收", next: "收放自如" },
    { idiom: "如鱼得水", next: "水涨船高" },
    { idiom: "高瞻远瞩", next: "瞩高瞩远" },
    { idiom: "远走高飞", next: "飞黄腾达" },
    { idiom: "达官贵人", next: "人定胜天" },
    { idiom: "天花乱坠", next: "坠茵落溷" },
    { idiom: "魂不守舍", next: "舍己为人" },
    { idiom: "人微言轻", next: "轻重倒置" },
    { idiom: "置之不理", next: "理直气壮" },
    { idiom: "壮气吞牛", next: "牛鬼蛇神" },
    { idiom: "神出鬼没", next: "没齿不忘" },
    { idiom: "忘恩负义", next: "义不容辞" },
    { idiom: "辞旧迎新", next: "新陈代谢" },
    { idiom: "谢天谢地", next: "地久天长" },
    { idiom: "长驱直入", next: "入木三分" },
    { idiom: "分秒必争", next: "争权夺利" },
    { idiom: "利欲熏心", next: "心猿意马" },
    { idiom: "马首是瞻", next: "瞻前顾后" },
    { idiom: "手舞足蹈", next: "蹈矩循规" },
    { idiom: "规行矩步", next: "步步为营" },
    { idiom: "营私舞弊", next: "弊绝风清" },
    { idiom: "清风明月", next: "月下老人" },
    { idiom: "人面桃花", next: "花言巧语" },
    { idiom: "语重心长", next: "长篇大论" },
    { idiom: "论功行赏", next: "赏心悦目" },
    { idiom: "目中无人", next: "人杰地灵" },
    { idiom: "灵丹妙药", next: "药到病除" },
    { idiom: "除恶务尽", next: "尽忠报国" },
    { idiom: "国泰民安", next: "安居乐业" },
    { idiom: "业精于勤", next: "勤能补拙" },
    { idiom: "拙口钝辞", next: "辞严义正" },
    { idiom: "正大光明", next: "明察秋毫" },
    { idiom: "毫不费力", next: "力不从心" }
];

// ===== 词语填空数据（100题） =====
const wordFillQuestions = [
    { sentence: "春天的花园里，百花___放，美丽极了。", answer: "绽", options: ["绽", "定", "锭"] },
    { sentence: "同学们在操场上___闹着，欢声笑语不断。", answer: "嬉", options: ["嬉", "嘻", "稀"] },
    { sentence: "天上的白云___态万千，有的像绵羊，有的像棉花糖。", answer: "姿", options: ["姿", "资", "滋"] },
    { sentence: "小明___精会神地听老师讲课。", answer: "聚", options: ["聚", "骤", "巨"] },
    { sentence: "秋天到了，树叶纷纷___落。", answer: "飘", options: ["飘", "漂", "瓢"] },
    { sentence: "这只小猫___态可掬，让人忍不住想摸摸它。", answer: "憨", options: ["憨", "敢", "赶"] },
    { sentence: "老师的话___入人心，让同学们深受感动。", answer: "深", options: ["深", "申", "伸"] },
    { sentence: "雨后，天空中出现了一道美丽的彩虹，___丽多彩。", answer: "绚", options: ["绚", "殉", "徇"] },
    { sentence: "同学们___不及待地想看新电影。", answer: "迫", options: ["迫", "泊", "伯"] },
    { sentence: "爷爷每天早上都会去公园___炼身体。", answer: "锻", options: ["锻", "段", "缎"] },
    { sentence: "小草从泥土里___出了嫩绿的芽。", answer: "钻", options: ["钻", "专", "砖"] },
    { sentence: "花园里的花___开了笑脸。", answer: "绽", options: ["绽", "定", "锭"] },
    { sentence: "同学们___跃举手回答问题。", answer: "踊", options: ["踊", "涌", "勇"] },
    { sentence: "这道题真让我___脑筋。", answer: "费", options: ["费", "废", "沸"] },
    { sentence: "___蓝的天空下，我们在草地上奔跑。", answer: "蔚", options: ["蔚", "尉", "慰"] },
    { sentence: "老师的话___移默化地影响着我。", answer: "潜", options: ["潜", "前", "遣"] },
    { sentence: "这棵大树___天蔽日，好凉快。", answer: "遮", options: ["遮", "折", "蔗"] },
    { sentence: "同学们___尽全力完成任务。", answer: "竭", options: ["竭", "结", "截"] },
    { sentence: "她___声朗读课文。", answer: "朗", options: ["朗", "浪", "廊"] },
    { sentence: "___面上波光粼粼，美极了。", answer: "湖", options: ["湖", "葫", "弧"] },
    { sentence: "小明___步如飞，跑得真快。", answer: "健", options: ["健", "建", "键"] },
    { sentence: "花园里百花___开。", answer: "盛", options: ["盛", "胜", "剩"] },
    { sentence: "同学们___守纪律。", answer: "遵", options: ["遵", "尊", "搏"] },
    { sentence: "老爷爷___发童颜，精神矍铄。", answer: "鹤", options: ["鹤", "贺", "赫"] },
    { sentence: "她___声细语地说话。", answer: "轻", options: ["轻", "青", "倾"] },
    { sentence: "___紫嫣红的花朵竞相开放。", answer: "姹", options: ["姹", "诧", "差"] },
    { sentence: "妈妈___尽职责地照顾我。", answer: "尽", options: ["尽", "近", "进"] },
    { sentence: "他___尽全力帮助别人。", answer: "竭", options: ["竭", "结", "截"] },
    { sentence: "这景色让人___连忘返。", answer: "流", options: ["流", "留", "榴"] },
    { sentence: "他___力而为，不过分勉强。", answer: "量", options: ["量", "良", "凉"] },
    { sentence: "___风习习，好凉快。", answer: "凉", options: ["凉", "梁", "粮"] },
    { sentence: "她___然大怒。", answer: "勃", options: ["勃", "脖", "博"] },
    { sentence: "同学们___头苦干。", answer: "埋", options: ["埋", "买", "卖"] },
    { sentence: "他___心沥血写出了好文章。", answer: "呕", options: ["呕", "欧", "偶"] },
    { sentence: "小草___壮成长。", answer: "茁", options: ["茁", "拙", "捉"] },
    { sentence: "花坛里的花___芳扑鼻。", answer: "芬", options: ["芬", "纷", "吩"] },
    { sentence: "同学们___心协力完成任务。", answer: "齐", options: ["齐", "奇", "骑"] },
    { sentence: "他___容满面地迎接客人。", answer: "笑", options: ["笑", "效", "小"] },
    { sentence: "___紫千红总是春。", answer: "万", options: ["万", "腕", "弯"] },
    { sentence: "老师___人不倦。", answer: "诲", options: ["诲", "悔", "毁"] },
    { sentence: "他___然泪下。", answer: "潸", options: ["潸", "删", "珊"] },
    { sentence: "这道题让我___思苦想。", answer: "绞", options: ["绞", "狡", "郊"] },
    { sentence: "___春白雪，高雅难懂。", answer: "阳", options: ["阳", "洋", "杨"] },
    { sentence: "他___心孤诣研究多年。", answer: "苦", options: ["苦", "枯", "哭"] },
    { sentence: "___塞顿开，终于明白了。", answer: "茅", options: ["茅", "矛", "茂"] },
    { sentence: "___然开朗，心情好了。", answer: "豁", options: ["豁", "活", "祸"] },
    { sentence: "老师___人不倦地教导我们。", answer: "循", options: ["循", "寻", "巡"] },
    { sentence: "他___规蹈矩，从不犯错。", answer: "循", options: ["循", "寻", "巡"] },
    { sentence: "花园___香四溢。", answer: "芬", options: ["芬", "纷", "吩"] },
    { sentence: "___色欲滴的草地真美。", answer: "翠", options: ["翠", "脆", "粹"] },
    { sentence: "他___然不动。", answer: "岿", options: ["岿", "归", "龟"] },
    { sentence: "___风细雨，润物无声。", answer: "和", options: ["和", "河", "荷"] },
    { sentence: "他___寝忘食地学习。", answer: "废", options: ["废", "费", "沸"] },
    { sentence: "___尽脑汁想出了答案。", answer: "绞", options: ["绞", "狡", "郊"] },
    { sentence: "老师___心教导我们。", answer: "苦", options: ["苦", "枯", "哭"] },
    { sentence: "他___强不息。", answer: "自", options: ["自", "字", "子"] },
    { sentence: "同学们___志昂扬。", answer: "斗", options: ["斗", "抖", "豆"] },
    { sentence: "___移默化地影响了我。", answer: "潜", options: ["潜", "前", "遣"] },
    { sentence: "___万变化。", answer: "千", options: ["千", "迁", "牵"] },
    { sentence: "___而复失。", answer: "得", options: ["得", "德", "的"] },
    { sentence: "___不容缓。", answer: "刻", options: ["刻", "克", "客"] },
    { sentence: "___苦钻研。", answer: "刻", options: ["刻", "克", "客"] },
    { sentence: "___发图强。", answer: "奋", options: ["奋", "粪", "份"] },
    { sentence: "___人为乐。", answer: "助", options: ["助", "柱", "住"] },
    { sentence: "___步如飞。", answer: "健", options: ["健", "建", "键"] },
    { sentence: "___在眉睫。", answer: "迫", options: ["迫", "泊", "伯"] },
    { sentence: "___然不同。", answer: "截", options: ["截", "结", "竭"] },
    { sentence: "___流不息。", answer: "奔", options: ["奔", "本", "笨"] },
    { sentence: "___光山色。", answer: "湖", options: ["湖", "葫", "弧"] },
    { sentence: "___卷云舒。", answer: "云", options: ["云", "允", "运"] },
    { sentence: "___飞凤舞。", answer: "龙", options: ["龙", "隆", "笼"] },
    { sentence: "___飞色舞。", answer: "眉", options: ["眉", "梅", "媒"] },
    { sentence: "___苦卓绝。", answer: "艰", options: ["艰", "坚", "间"] },
    { sentence: "___往直前。", answer: "勇", options: ["勇", "涌", "永"] },
    { sentence: "___首挺胸。", answer: "昂", options: ["昂", "仰", "枊"] },
    { sentence: "___步当车。", answer: "安", options: ["安", "按", "岸"] },
    { sentence: "___弓射雕。", answer: "弯", options: ["弯", "湾", "碗"] },
    { sentence: "___马观花。", answer: "走", options: ["走", "奏", "揍"] },
    { sentence: "___蛇添足。", answer: "画", options: ["画", "话", "化"] },
    { sentence: "___鸡起舞。", answer: "闻", options: ["闻", "文", "温"] },
    { sentence: "___釜沉舟。", answer: "破", options: ["破", "坡", "波"] },
    { sentence: "___耳盗铃。", answer: "掩", options: ["掩", "眼", "演"] },
    { sentence: "___苗助长。", answer: "揠", options: ["揠", "压", "鸭"] },
    { sentence: "___壁偷光。", answer: "凿", options: ["凿", "早", "造"] },
    { sentence: "___心沥血。", answer: "呕", options: ["呕", "欧", "偶"] },
    { sentence: "___风沐雨。", answer: "栉", options: ["栉", "挚", "至"] },
    { sentence: "___荆斩棘。", answer: "披", options: ["披", "批", "砒"] },
    { sentence: "___河山壮。", answer: "大", options: ["大", "达", "答"] },
    { sentence: "___容可掬。", answer: "憨", options: ["憨", "敢", "赶"] },
    { sentence: "___气风发。", answer: "意", options: ["意", "义", "易"] },
    { sentence: "___马行空。", answer: "天", options: ["天", "添", "田"] },
    { sentence: "___水楼台。", answer: "近", options: ["近", "进", "尽"] },
    { sentence: "___物思人。", answer: "睹", options: ["睹", "赌", "堵"] },
    { sentence: "___理力争。", answer: "据", options: ["据", "居", "局"] },
    { sentence: "___往开来。", answer: "继", options: ["继", "计", "记"] },
    { sentence: "___目相看。", answer: "刮", options: ["刮", "瓜", "挂"] },
    { sentence: "___火纯青。", answer: "炉", options: ["炉", "芦", "鲁"] },
    { sentence: "___壤之别。", answer: "天", options: ["天", "添", "田"] },
    { sentence: "___兵必胜。", answer: "哀", options: ["哀", "唉", "挨"] },
    { sentence: "___能可贵。", answer: "难", options: ["难", "南", "男"] }
];
